Feat/Header, button, input
woohoo1607/manager pull request #1
Opened 2021-01-20 14:00 UTC by woohoo1607

2021-01-20 15:05 UTC, oleksandrbazil requested changes
Постарайся ответить на вопросы (прямо в треде), если поймешь что и как можно исправить - исправь. После этого давай посмотрим на код вместе, окей?

2021-01-20 15:05 UTC, oleksandrbazil commented on .eslintcache
> +[{"/home/bro/Документи/manager/src/App.js":"1","/home/bro/Документи/manager/src/index.js":"2","/home/bro/Документи/manager/src/components/Header/Header.js":"3","/home/bro/Документи/manager/src/report
надо сделать так что бы этот файл больше не попадал в repository

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Button/Button.js
> +const Button = ({ type = "primary", title, onClick }) => {
что произойдет если я передам неправильный тип? например type="priimary"

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Button/styles.css
> +}
github подсвечивает ошибку `No newline at end of file`
найди плз ответ почему это ошибка и исправь ее

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Header/Header.js
> +  console.log(pathname);
В коммиты не должны попадать такие строки как
- console.log
- закоментированный код - есть негласное правило "закоментированный код - мертвый код"
Убери такие строки если они еще где-то есть и постарайся не добавлять в следующие коммиты такие строки

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Header/Header.js
> +                    pathname === "/" ? "menu-link active-link" : "menu-link"
проверка  `pathname === "/"` повторяется более одного раза -> нужно выносить в переменную и переиспользовать

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Header/Header.js
> +                    pathname === "/add-user"
то же правило что и выше

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Header/styles.css
> +#list-of-users-icon path {
закомментированный код

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Input/Input.js
> +                  background: `url(${EyeStrike}) center center no-repeat`,
линия 36 и 39 практически идентичны, что можно сделать?
как можно написать короче?

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Input/Input.js
> +import Calendar from "../../icons/calendar.svg";
Наименование компонентов не очень удачное, что будешь делать если нужно использовать иконки в компоненте который называется `Calendar`?

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Input/Input.js
> +const Input = ({ title, inputType = "text", isRequired = false }) => {
а почему положил компонент в папку Input и назвал файл Input?
Как можно сделать по другому?

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Input/Input.js
> +    }
как можно сократить написание с 5 линий кода до 1?

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Input/Input.js
> +          className="input-img"
смотри что получаеться:
1) дважды пишем 
```
<button
          className="input-img"
```
2) логика инпутов Пароля и Даты находиться в 1 компоненте, при этом стейт для Пароля используется только к паролю, а для Даты он априори не будет нужен. 
Что можно сделать как думаешь?

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Input/Input.js
> +const Input = ({ title, inputType = "text", isRequired = false }) => {
а что поменяться если не задавать `isRequired = false`?

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Header/Header.js
> +  const pathname = history.location.pathname;
как можно вытянуть pathname безопасным путем что бы ни при каких обстоятельствах (пустой history обьект) приложение не упало?

2021-01-20 15:05 UTC, oleksandrbazil commented on src/components/Header/Header.js
> +import { ReactComponent as ListOfUsers } from "../../icons/list-of-users.svg";
а почему таким образом импортируются иконки?

2021-01-20 15:05 UTC, oleksandrbazil commented on package.json
> +    "redux": "^4.0.5",
Напиши, пожалуйста за что отвечает каждая зависимость и зачем мы ее добавляем:
- formik
- react-indexed-db
- react-redux
- react-select
- web-vitals

2021-01-20 15:16 UTC, woohoo1607 commented on .eslintcache
> +[{"/home/bro/Документи/manager/src/App.js":"1","/home/bro/Документи/manager/src/index.js":"2","/home/bro/Документи/manager/src/components/Header/Header.js":"3","/home/bro/Документи/manager/src/report
ок

2021-01-20 15:21 UTC, woohoo1607 commented on src/components/Button/Button.js
> +const Button = ({ type = "primary", title, onClick }) => {
ничего=) нужно вынести наверное все возможные типы в массив с их значениями.

2021-01-20 15:24 UTC, woohoo1607 commented on src/components/Button/styles.css
> +}
я так понял что файл должен заканчиваться пустой строкой

2021-01-20 15:24 UTC, woohoo1607 commented on src/components/Header/Header.js
> +  console.log(pathname);
ок

2021-01-20 15:29 UTC, woohoo1607 commented on src/components/Header/Header.js
> +                    pathname === "/" ? "menu-link active-link" : "menu-link"
исправил

2021-01-20 15:30 UTC, woohoo1607 commented on src/components/Header/styles.css
> +#list-of-users-icon path {
каюсь не заметил=)

2021-01-20 15:30 UTC, woohoo1607 commented on src/components/Header/Header.js
> +                    pathname === "/add-user"
исправил

2021-01-20 15:32 UTC, woohoo1607 commented on src/components/Input/Input.js
> +                  background: `url(${EyeStrike}) center center no-repeat`,
переписал

2021-01-20 15:33 UTC, woohoo1607 commented on src/components/Input/Input.js
> +import Calendar from "../../icons/calendar.svg";
добавил в конце "Icon"=)

2021-01-20 15:34 UTC, woohoo1607 commented on src/components/Input/Input.js
> +const Input = ({ title, inputType = "text", isRequired = false }) => {
можна файл назвать index.js

2021-01-20 15:35 UTC, woohoo1607 commented on src/components/Input/Input.js
> +    }
тернарным оператором

2021-01-20 15:40 UTC, woohoo1607 commented on src/components/Input/Input.js
> +const Input = ({ title, inputType = "text", isRequired = false }) => {
разве что код станет короче=)

2021-01-20 15:40 UTC, woohoo1607 commented on src/components/Header/Header.js
> +  const pathname = history.location.pathname;
через window?

2021-01-20 15:40 UTC, woohoo1607 commented on src/components/Header/Header.js
> +import { ReactComponent as ListOfUsers } from "../../icons/list-of-users.svg";
что бы я потом мог этим svg менять цвет

2021-01-20 15:48 UTC, woohoo1607 commented on package.json
> +    "redux": "^4.0.5",
1. formik - либа для работы с формами
2. react-indexed-db - либа для работы с IndexedDb
3. react-redux - для связывания реакте с редаксом (П.С. только что задумался что если юзать только хуки, то она не нужна будет)
4. react-select - либа для работы с Selec
5. web-vitals - не знаю откуда она тут взялась, но насколько я понял это либа гугла для измерения определенных метрик сайта

2021-01-20 15:52 UTC, oleksandrbazil commented on .eslintcache
> +[{"/home/bro/Документи/manager/src/App.js":"1","/home/bro/Документи/manager/src/index.js":"2","/home/bro/Документи/manager/src/components/Header/Header.js":"3","/home/bro/Документи/manager/src/report
файл удалил 👍 , а он может повторно попасть в коммит? :)

2021-01-20 15:58 UTC, oleksandrbazil commented on src/components/Button/styles.css
> +}
верно, а почему есть такое правило?

2021-01-20 16:15 UTC, oleksandrbazil commented on src/components/Header/Header.js
> +  const pathname = history.location.pathname;
деструктуризация

2021-01-20 16:29 UTC, oleksandrbazil commented on src/routes/routes.js
> +      <Route exact path="/add-user" render={(props) => <div {...props} />} />
переименовать роуты согласно CRUD

2021-01-20 16:29 UTC, oleksandrbazil commented on src/routes/routes.js
> +      <Route exact path="/add-user" render={(props) => <div {...props} />} />
почитай разницу между REST и CRUD

2021-01-20 16:29 UTC, oleksandrbazil commented on src/components/Layout/Layout.js
> +    <div className="App">
класс App должен лежать в компоненте App
надо разобраться с 
- Page Component
- Layout Component
- App Component
куда добавлять Routes?

2021-01-21 08:13 UTC, oleksandrbazil approved these changes

2021-01-21 08:23 UTC, merged