Feat/edit user page
woohoo1607/manager pull request #11
Opened 2021-02-02 22:40 UTC by woohoo1607

2021-02-03 08:25 UTC, oleksandrbazil requested changes

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +          type="submit"
https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element
> The missing value default and invalid value default are the Submit Button state.

вот по этому по умолчанию лучше проставлять тип submit

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +          {isLastStep ? "Finish" : "Forward"}
попробуй переписать так что бы не было второй проверки isLastStep (первая на 22 строчке)

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const [allowedTabs, setAllowedTabs] = useState([0]);
почему решил хранить эти данные в state?

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +      setAllowedTabs([...allowedTabs, activeStep + 1]);
второй раз пишешь `activeStep + 1`, что нужно сделать?

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +    changeUrl(findTitleTab(activeStep + 1));
четвертый

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const [activeStep, setActiveStep] = useState(activeTab);
а если бы был выбор как назвать переменную, что бы ты выбрал: `activeStep` или `currentStep`?

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const findTitleTab = (i) => steps[i].title.toLowerCase();
что произойдет если в заголовке будет пробел? а если будет знак вопроса?

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +          submit={isLastStep || isEditMode ? submit : nextStep}
этой логике здесь не место

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/StepWizard/styles.css
> +.step-wizard-menu__button:hover:enabled {
👍

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/UserInformation/index.js
> +          handleClick={goToEditUser("profile")}
потенциальный баг

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/UsersTable/RowItem.js
> +              top: "40%",
а почему стили передаешь через style?

2021-02-03 08:25 UTC, oleksandrbazil commented on src/components/UsersTable/index.js
> +  const [activeRow, setActiveRow] = useState(NO_ACTIVE_ROW);
а что ты имеешь ввиду под  activeRow?

2021-02-03 08:25 UTC, oleksandrbazil commented on src/pages/EditUserPage/index.js
> +  const tabName = history.location.pathname.split("/edit/")[1];
кто тебя научил так писать код? :)

2021-02-03 08:25 UTC, oleksandrbazil commented on src/pages/EditUserPage/index.js
> +    (step) => step.title.toLowerCase() === tabName
место очередного потенциального бага
скажи, пожалуйста, в чем тут проблема?

2021-02-03 08:25 UTC, oleksandrbazil commented on src/pages/EditUserPage/index.js
> +  const push = history.push;
WTF?

2021-02-03 08:25 UTC, oleksandrbazil commented on src/pages/EditUserPage/index.js
> +  user.id = 0;
WTF?

2021-02-03 08:25 UTC, oleksandrbazil commented on src/pages/EditUserPage/index.js
> +        isEditMode={true}
🤦

2021-02-03 08:25 UTC, oleksandrbazil commented on src/pages/EditUserPage/index.js
> +  const changeUrl = (tab = "") => push(`/users/${user.id}/edit/${tab}`);
деструктуризируй все что можно деструктуризировать

2021-02-03 08:25 UTC, oleksandrbazil commented on src/routes/index.js
> +        path="/users/:id/edit/"
а почему так?

2021-02-03 12:43 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardControls.js
> +          type="submit"
исправил

2021-02-03 12:57 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const [allowedTabs, setAllowedTabs] = useState([0]);
ну а где еще их хранить?=)

2021-02-03 13:08 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +      setAllowedTabs([...allowedTabs, activeStep + 1]);
переписал

2021-02-03 13:08 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +    changeUrl(findTitleTab(activeStep + 1));
переписал

2021-02-03 13:09 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const [activeStep, setActiveStep] = useState(activeTab);
currentStep=)
П.С. исправил

2021-02-03 13:16 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const findTitleTab = (i) => steps[i].title.toLowerCase();
добавил для форм свойство urlName

2021-02-03 13:19 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +          submit={isLastStep || isEditMode ? submit : nextStep}
перенес

2021-02-03 13:21 UTC, woohoo1607 commented on src/components/UserInformation/index.js
> +          handleClick={goToEditUser("profile")}
из-за того что прокидываем строку с названием?

2021-02-03 13:31 UTC, woohoo1607 commented on src/components/UsersTable/RowItem.js
> +              top: "40%",
вынес

2021-02-03 13:32 UTC, woohoo1607 commented on src/components/UsersTable/index.js
> +  const [activeRow, setActiveRow] = useState(NO_ACTIVE_ROW);
строка которая после клика на кнопу delete сместилась в сторону и поменяла дизайн=)

2021-02-03 13:37 UTC, woohoo1607 commented on src/pages/EditUserPage/index.js
> +    (step) => step.title.toLowerCase() === tabName
если название будет со спец символами или еще чем-то то будет плохо url`у
я пока-что добавил urlName в steps

2021-02-03 13:47 UTC, woohoo1607 commented on src/pages/EditUserPage/index.js
> +  const tabName = history.location.pathname.split("/edit/")[1];
сам научился =))
П.С. поразмыслил и переписал=)

2021-02-03 13:48 UTC, woohoo1607 commented on src/pages/EditUserPage/index.js
> +  const push = history.push;
переписал

2021-02-03 13:49 UTC, woohoo1607 commented on src/pages/EditUserPage/index.js
> +  user.id = 0;
та у меня у юзера там id нету, потому что его будет БД присваивать, вот для проверки добавил. Я там TODO написал что удалить надо его после того как БД подключу=)

2021-02-03 13:51 UTC, woohoo1607 commented on src/pages/EditUserPage/index.js
> +        isEditMode={true}
удалил true=)

2021-02-03 13:52 UTC, woohoo1607 commented on src/routes/index.js
> +        path="/users/:id/edit/"
сделал users/:id/edit/:tabName что бы можно было название вкладки с урла вытягивать

2021-02-03 13:52 UTC, oleksandrbazil commented on src/components/UsersTable/index.js
> +  const [activeRow, setActiveRow] = useState(NO_ACTIVE_ROW);
как насчет другого названия, например: selectedRow?

2021-02-03 13:58 UTC, oleksandrbazil commented on src/pages/EditUserPage/index.js
> +    (step) => step.title.toLowerCase() === tabName
понял, хорошо, есть еще одна просьба - используй slug вместо urlName.

2021-02-03 13:59 UTC, oleksandrbazil commented on src/pages/EditUserPage/index.js
> +  const changeUrl = (tab = "") => push(`/users/${user.id}/edit/${tab}`);
деструтуризировал?  :)

2021-02-03 14:12 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardHeader.js
> +  changeUrl = () => {},
чем отличается goToStep и changeUrl?

2021-02-03 14:12 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const [currentStep, setCurrentStep] = useState(currentTab);
зачем currentTab ?

2021-02-03 14:12 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  };
а зачем индексы?

2021-02-03 14:12 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +  },
кажется я где-то писал про форматирование строк, помнишь?

2021-02-03 14:12 UTC, oleksandrbazil commented on src/routes/index.js
> +        path="/users/:id/edit/:tabName"
это точно tabName? какое лучше дать название?

2021-02-03 14:13 UTC, woohoo1607 commented on src/components/UsersTable/index.js
> +  const [activeRow, setActiveRow] = useState(NO_ACTIVE_ROW);
так звучит лучше=) исправил

2021-02-03 14:17 UTC, woohoo1607 commented on src/pages/EditUserPage/index.js
> +    (step) => step.title.toLowerCase() === tabName
переписал

2021-02-03 14:30 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardHeader.js
> +  changeUrl = () => {},
одна функция меняет URL а другая номер вкладки, сделал ф-цию которая делает это все, и передаю теперь только одну

2021-02-03 14:35 UTC, woohoo1607 commented on src/routes/index.js
> +        path="/users/:id/edit/:tabName"
дал slug как ты написал выше

2021-02-03 14:43 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const [currentStep, setCurrentStep] = useState(currentTab);
когда форма редактирования, то мы можем со старта прыгнуть на любую вкладку, в этом случае я передаю currentTab. Я переименовал в currentTabIndex, так вроде бы понятнее

2021-02-03 14:46 UTC, woohoo1607 commented on src/pages/EditUserPage/index.js
> +  const changeUrl = (tab = "") => push(`/users/${user.id}/edit/${tab}`);
если ты про id, то да, вытягиваю его с урла=)

2021-02-03 14:49 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  };
что бы можно было определить последний это шаг или нет, что бы можно было вытянуть нужное название для url, ну и по ним StepWizard преключает вкладки

2021-02-03 14:52 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +  },
поправил под один стиль, просто prettier сам их то переносит, то наоборот собирает

2021-02-03 14:58 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardControls.js
> +          {isLastStep ? "Finish" : "Forward"}
https://github.com/woohoo1607/manager/pull/11/commits/47c9c0c43781e085399c8d9964ef0d02aa8450ec

2021-02-03 15:42 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +  },
а prettier конфиг добавлен в проект?

2021-02-04 08:15 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardHeader.js
> +  const changeStep = (slug) => () => {
не вижу особого смысла в этой функции:
- либо пиши инлайном 
- либо дай ей название через handle

2021-02-04 08:15 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const currentSlug = pathname.split(`${basePath}/`)[1] || steps[0].slug;
выглядит ненадежно

2021-02-04 08:15 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +    )[0];
что тут надо сдлеать?

2021-02-04 08:15 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  console.log(specialStepsData);
ну как так?

2021-02-04 08:15 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +                  /*     previousStep={previousStep}*/
почему ты комитишь закоментированный код?

2021-02-04 08:16 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +                  /*     previousStep={previousStep}*/
только сейчас увидел
@woohoo1607
intermediate changes for me
c86d132
@woohoo1607
commit for me

2021-02-04 08:17 UTC, oleksandrbazil commented
пожалуйста, нажми кнопку запросить ревью когда доделаешь

2021-02-04 12:25 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +  isFirstStep = 0,
is это приставка для Boolean переменных, а тут значение по умолчанию = 0 
:(

2021-02-04 12:25 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardHeader.js
> +            if (slug === currentSlug) {
className можно написать короче

2021-02-04 12:25 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const [allowedSteps, setAllowedSteps] = useState([steps[0].slug]);
выглядит не очень

2021-02-04 12:25 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +import React, { useCallback } from "react";
а где используется useCallback ?

2021-02-04 20:49 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +import React, { useCallback } from "react";
для диспатча данных с форм в редакс

2021-02-05 08:57 UTC, oleksandrbazil requested changes

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/Button/index.js
> +const Button = ({ type = "submit", children, className, ...props }) => {
а почему не вынес Button в UI ?

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardHeader.js
> +            const className = isCurrentStep ? "current" : "primary";
1. как думаешь есть смысл в том что бы выносить className в переменную?
2. классы кнопке навешиваются по БЭМ?
3. какой type должен быть у этих кнопок?

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +      ) : isLastStep ? (
старайся писать без использования двойного тернарного оператора - это сложнее читать
`true1 ? true2 ? 'yes' : 'no' : 'no'`
```
if (true1) {
 true2 ? 'yes' : 'no'
} else {
 'no'
}
```

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +      {!isFirstStep && !isEditMode && (
попробуй переписать так что бы isEditMode проверка происходила только 1 раз

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +      path={[`${match.url}/:slug`, match.url]}
может все-таки было бы лучше деструктуризировать? зачем писать одно и то же ?
**Don’t repeat yourself**

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +        push(`${path}/${steps[0].slug}`);
**Don’t repeat yourself**

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const currentStepIndex = steps.findIndex((step) => step.slug === slug);
**Destructuring assignment**

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const isFirstStep = steps[0].slug === slug;
**Don’t repeat yourself**

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +    const nextStepSlug = steps[currentStepIndex + 1].slug;
**Variable used only once**

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const submitForm = isLastStep || isEditMode ? submit : nextStep;
**Variable used only once**

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +          isAllowed: isEditMode || i <= allowedUnsubmittedStep,
я немного подумал, и мне кажется что лучший вариант это объявить
- currentStep - шаг форму которого нужно заполнить для продвижения по форме
- activeStep - шаг на котором сейчас пользователь находиться 

тогда все сложиться правильно: у тебя будет 2 переменные, и отображение синей кнопки в навигации будет корректным (на основе activeStep)

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/UserInformation/index.js
> +        <InformationBlock title="Account" handleClick={goToEditUser("account")}>
добавь комментарий TODO: refactor with STEPS usage

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/UserStepWizard/StepWizardControls.js
> +const StepWizardControls = ({
зачем  еще один StepWizardControls компонент?

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/UserStepWizard/StepWizardHeader.js
> +const StepWizardHeader = ({
зачем еще один StepWizardHeader компонент?

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/UsersTable/RowItem.js
> +    <TableRow className={isSelected ? "active" : ""}>
а класс останется active?

2021-02-05 08:57 UTC, oleksandrbazil commented on src/components/UsersTable/RowItem.js
> +          <Button type="button" className="delete-row" onClick={deleteUser(id)}>
почему название `delete-row`?
ты же не называешь `телефон`  как `позвонить кому-либо` ?

2021-02-05 08:57 UTC, oleksandrbazil commented on src/pages/EditUserPage/index.js
> +  const user = useSelector((state) => state.user);
это временное решение или нет?

2021-02-05 09:04 UTC, woohoo1607 commented on src/components/Button/index.js
> +const Button = ({ type = "submit", children, className, ...props }) => {
перенес

2021-02-05 09:17 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardHeader.js
> +            const className = isCurrentStep ? "current" : "primary";
1. После изменений не подумал что переменная уже не нужна=)
2. Тут еще поразсмыслю и перечитаю=)
3. type='button'  - добавил

2021-02-05 09:22 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardControls.js
> +      ) : isLastStep ? (
с этим полностью согласен, но я ж там не могу использовать if

2021-02-05 09:37 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardControls.js
> +      {!isFirstStep && !isEditMode && (
ну чет намудрил, посмотришь =)

2021-02-05 09:38 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +      path={[`${match.url}/:slug`, match.url]}
done

2021-02-05 09:39 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +        push(`${path}/${steps[0].slug}`);
вынес в переменную

2021-02-05 09:41 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const currentStepIndex = steps.findIndex((step) => step.slug === slug);
Сделал

2021-02-05 09:42 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const isFirstStep = steps[0].slug === slug;
сделал переменную firstStepSlug

2021-02-05 09:43 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +    const nextStepSlug = steps[currentStepIndex + 1].slug;
done

2021-02-05 09:44 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const submitForm = isLastStep || isEditMode ? submit : nextStep;
done

2021-02-05 09:45 UTC, woohoo1607 commented on src/components/UserInformation/index.js
> +        <InformationBlock title="Account" handleClick={goToEditUser("account")}>
done

2021-02-05 09:45 UTC, woohoo1607 commented on src/components/UserStepWizard/StepWizardControls.js
> +const StepWizardControls = ({
не заметил, что скопировал случайно, удалил

2021-02-05 09:45 UTC, woohoo1607 commented on src/components/UserStepWizard/StepWizardHeader.js
> +const StepWizardHeader = ({
не заметил, что скопировал случайно, удалил

2021-02-05 09:47 UTC, woohoo1607 commented on src/components/UsersTable/RowItem.js
> +    <TableRow className={isSelected ? "active" : ""}>
переписал

2021-02-05 09:48 UTC, woohoo1607 commented on src/components/UsersTable/RowItem.js
> +          <Button type="button" className="delete-row" onClick={deleteUser(id)}>
delete-selected-row лучше будет звучать?

2021-02-05 09:53 UTC, woohoo1607 commented on src/pages/EditUserPage/index.js
> +  const user = useSelector((state) => state.user);
сделал там деструктуризацию, а по поводу временное или нет, то точно не окончательное=)
и не совсем понял что тут не нравится=)

2021-02-05 09:58 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +      ) : isLastStep ? (
а что можно сделать в этом случае? когда нельзя if но нужно где-то разместить логику отображения?

2021-02-05 10:00 UTC, oleksandrbazil commented on src/components/UsersTable/RowItem.js
> +          <Button type="button" className="delete-row" onClick={deleteUser(id)}>
нет, не пытайся назвать класс действием, ты даешь имя тэгу/компоненту - имя существительное

2021-02-05 10:02 UTC, oleksandrbazil commented on src/pages/EditUserPage/index.js
> +  const user = useSelector((state) => state.user);
это edit user page - на ней берется какой-то пользователь по айдишнику, а форму ты берешь new user (создание пользователя)
я правильно понимаю?

2021-02-05 10:13 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +  let submitButtonTitle = "";
ну практически угадал :) 
а ты можешь положить Button в переменную?

2021-02-05 10:13 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +      path={[`${url}/:slug`, url]}
почему тут массив?

2021-02-05 10:13 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +      if (slug !== firstStepSlug && !isEditMode)
зачем второй уровень if?

2021-02-05 10:13 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const changeStep = (slug) => {
ну можно же написать в 1 строку?

2021-02-05 10:13 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const previousStep = () => changeStep(steps[currentStepIndex - 1].slug);
напомни мне об этом куске кода после обеда

2021-02-05 12:14 UTC, woohoo1607 commented on src/pages/EditUserPage/index.js
> +  const user = useSelector((state) => state.user);
а ты про данные которые из редакса беру? я редьюсеры думаю все в одну папку скину

2021-02-05 12:22 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +      path={[`${url}/:slug`, url]}
что бы пропускало по урлу в котором нет :slug

2021-02-05 13:02 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +      if (slug !== firstStepSlug && !isEditMode)
переписал проверку

2021-02-05 13:03 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const changeStep = (slug) => {
ага

2021-02-05 15:41 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +  return <div className="step-wizard__controls">{controls}</div>;
вынеси controls в компопнет который будет обьявлен в этом файле и назови его ControlButtons

2021-02-05 15:41 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +      ? controls.push(
старайся использовать тернарный оператор только тогда когда можно поместить все в 1 строку

2021-02-05 15:41 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +      className="step-wizard__button step-wizard__button-back"
😭  DRY

2021-02-07 13:27 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +  children = "Save",
значение по умолчанию лучше дать `title` а не `children`

2021-02-07 14:27 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +          <ControlButton
тут класс не надо передавать, нужно использовать  :) попробуй переписать что бы использовать "вариант" кнопки

2021-02-08 07:24 UTC, merged