Style/UI refactor
woohoo1607/manager pull request #12
Opened 2021-02-08 07:38 UTC by woohoo1607

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/DateInput/styles.css
> +    mask: url("../../icons/back.svg") 50% 50% no-repeat;
почему сделал именно таким образом?

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/SelectInput/index.js
> +        return { ...currentValue, label: currentValue.label.slice(0, 3) };
а что такое .slice(0, 3) ?
что будет если не найдешь currentValue?

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/SelectInput/index.js
> +      if (isMulti) {
нам надо второй уровень вложенности if?

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/UI/Avatar/index.js
> +      <UserIcon className="avatar default" />
а в чем разница между 
-  <img className="avatar" ...
-  <UserIcon ...

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/UI/FileInputBase/index.js
> +      accept="image/png, image/jpeg, image/jpg"
проверку нужно делать по другому, это решение плохо поддерживается 
https://caniuse.com/input-file-accept

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/UI/FileInputBase/styles.css
> +.file-input:focus-within {
почему такое решение?
https://caniuse.com/?search=focus-within

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/UI/IconButton/index.js
> +    {React.cloneElement(children, { className: "icon-button__icon" })}
зачем тут React.cloneElement ?

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/UI/Input/index.js
> +        isSecondaryColor ? "input-secondary" : ""
почему этот параметр используется в другом компоненте?

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/UserForms/AccountForm.js
> +      value ? value.size <= MAX_PHOTO_SIZE : true
деструктуризация?

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/UserForms/ContactsForm.js
> +const URL = /((https?):\/\/)?(www.)?[a-z0-9]+(\.[a-z]{2,}){1,3}(#?\/?[a-zA-Z0-9#]+)*\/?(\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+&?)?$/;
сам писал?

2021-02-08 15:23 UTC, oleksandrbazil commented on src/components/UserForms/ContactsForm.js
> +                    borderRadius: "50%",
почему не вынес в styles?

2021-02-08 15:23 UTC, oleksandrbazil commented on src/pages/NewUserPage/reducer.js
> +      if (payload.hasOwnProperty("phones")) {
а тебе компилятор/консоль не ругается на эту строку?

2021-02-08 15:23 UTC, oleksandrbazil commented on src/pages/NewUserPage/reducer.js
> +        payload.phones = payload.phones.filter((phone) => phone.length > 0);
почему логика находиться в reducer?

2021-02-08 15:23 UTC, oleksandrbazil commented on src/pages/UserPage/index.js
> +    <TemplatePage title={user.username} backLink="/" linkTitle="Users List">
деструктуризация?

2021-02-08 15:29 UTC, woohoo1607 commented on src/components/DateInput/styles.css
> +    mask: url("../../icons/back.svg") 50% 50% no-repeat;
нашел в либе где юзаются ее елементы, и заменил на свои. По поводу mask, то нашел такое решение как вставить svg в бекграунд

2021-02-08 16:21 UTC, woohoo1607 commented on src/components/UserForms/ContactsForm.js
> +const URL = /((https?):\/\/)?(www.)?[a-z0-9]+(\.[a-z]{2,}){1,3}(#?\/?[a-zA-Z0-9#]+)*\/?(\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+&?)?$/;
URLPattern

2021-02-09 07:59 UTC, woohoo1607 commented on src/pages/UserPage/index.js
> +    <TemplatePage title={user.username} backLink="/" linkTitle="Users List">
В следующем пуле исправлю, тут все равно замоканные данные

2021-02-09 08:18 UTC, oleksandrbazil requested changes

2021-02-09 08:18 UTC, oleksandrbazil commented on src/components/SelectInput/index.js
> +      return options.find((option) => option.value === value) || "";
выглядит все равно странно: find вернет обьект, а по умолчанию возвращается пустая строка

2021-02-09 08:18 UTC, oleksandrbazil commented on src/components/UI/IconButton/index.js
> +  isMinusIcon = false,
у тебя есть случай когда нужно будет отобразить 2 иконки в одной кнопке? если нет, то решение через Boolean не подходит

2021-02-09 08:18 UTC, oleksandrbazil commented on src/components/UI/IconButton/styles.css
> +    position: absolute;
🧐

2021-02-09 08:18 UTC, oleksandrbazil commented on src/components/UserForms/ContactsForm.js
> +const URLPattern = /((https?):\/\/)?(www.)?[a-z0-9]+(\.[a-z]{2,}){1,3}(#?\/?[a-zA-Z0-9#]+)*\/?(\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+&?)?$/;
это константа? если да, то почему у нее такое название?

2021-02-09 08:26 UTC, woohoo1607 commented on src/components/UserForms/ContactsForm.js
> +const URLPattern = /((https?):\/\/)?(www.)?[a-z0-9]+(\.[a-z]{2,}){1,3}(#?\/?[a-zA-Z0-9#]+)*\/?(\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+&?)?$/;
все большими должно быть?

2021-02-09 08:40 UTC, woohoo1607 commented on src/components/SelectInput/index.js
> +      return options.find((option) => option.value === value) || "";
исправил

2021-02-09 08:41 UTC, woohoo1607 commented on src/components/UI/IconButton/styles.css
> +    position: absolute;
ой не туда вставил стиль=)

2021-02-09 09:01 UTC, woohoo1607 commented on src/components/UI/IconButton/index.js
> +  isMinusIcon = false,
переписал

2021-02-09 13:35 UTC, oleksandrbazil approved these changes

2021-02-09 14:00 UTC, merged