Feat/indexed db
woohoo1607/manager pull request #13
Opened 2021-02-09 14:02 UTC by woohoo1607

2021-02-09 15:17 UTC, oleksandrbazil requested changes

2021-02-09 15:17 UTC, oleksandrbazil commented on package.json
> +    "dayjs": "^1.10.4",
зачем он нам?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/PopUp/index.js
> +import PopUpWindow from "../UI/PopUpWindow";
попап - не лучшее название, обычно попап это элемент на весь экран, и пока ты его не закроешь ничего кликать нельзя

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/PopUp/index.js
> +      setTimeout(() => dispatch(closePopUp()), 6000);
🧐

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/PopUp/index.js
> +  return <>{isOpen && <PopUpWindow msg={msg} variant={variant} />}</>;
через тернарный оператор будет проще?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/PopUp/index.js
> +  const { isOpen, msg, variant } = useSelector(({ popup }) => popup);
не нужно сокращать переменные, старайся писать полноценно

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  unsavedData = null,
почему null ?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +    const { slug } = steps[currentStepIndex + 1] || {};
будет забавно когда `currentStepIndex` прилетит -1

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +        {unsavedData && (
пожалуйста, переименуй в булевоподобную переменную

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/UI/PopUpWindow/index.js
> +      <p>{msg}</p>
не гибкий вариант, а если понадобиться прокинуть msg с двумя абзацами? :)

2021-02-09 15:17 UTC, oleksandrbazil commented on src/App.css
> +  --primary-bg-color: #5E97F3;
зачем приставка bg?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/UserForms/ProfileForm.js
> +      (value) => dayjs().diff(dayjs(value), "years") >= 18
что будешь делать когда где-то нужно будет проверять 21 год? сколько мест нужно будет изменить?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/UserInformation/styles.css
> +.user-information-block > .user-information-title {
почему только первому тэгу?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/UsersTable/RowItem.js
> +  dayjs.extend(relativeTime);
что делает эта строчка кода?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/UsersTable/RowItem.js
> +      <TableCell>{`${dayjs(lastUpdate).fromNow(true)} ago`}</TableCell>
а какой тип данных храниться в lastUpdate?
что произойдет если там будет undefined?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/UsersTable/index.js
> +          <TableHeadCell style={{ minWidth: "125px" }}>
а почему переписал в пиксели?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/components/UsersTable/index.js
> +        {users.map((item, i) => (
в каких случаях можно задавать `key={i}` ?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/helpers/convertBlobToBase64.js
> +  return new Promise((resolve) => {
а что будет при reject?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/helpers/dataURItoBlob.js
> +  const byteString = atob(dataURI.split(",")[1]);
снова стучимся по индексу? может тут что-то пойти не так?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/helpers/dataURItoBlob.js
> +  const mimeString = dataURI.split(",")[0].split(":")[1].split(";")[0];
😭

2021-02-09 15:17 UTC, oleksandrbazil commented on src/helpers/dataURItoBlob.js
> +  const _ia = new Uint8Array(arrayBuffer);
почему переменная начинается с нижним подчеркиванием?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/helpers/localStorageHelper.js
> +export const getData = async (name) =>
какой параметр прилетает? где проверки? что вернет?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/icons/Spinner.svg
> +<!-- [ldio] generated by https://loading.io/ --></svg>
где последняя строка в файле?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +  const savePart = useCallback((data) => dispatch(addAccountData(data)), [
не понятно что делает функция

2021-02-09 15:17 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +  const createUser = useCallback((user) => dispatch(addUser(user)), [dispatch]);
почему в useCallback?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +    (async () => {
что здесь происходит?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/reducers/actions.js
> +  delete newUser.allowedUnsubmittedStep;
зачем это поле newUser?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/reducers/actions.js
> +const removeUnnecessaryUserProperties = (user) => {
а можешь сгруппировать переменные и функции для Redux согласно сущности?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/reducers/popupReducer.js
> +  variant: "primary",
зачем это?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/sagas/userSaga.js
> +      const res = yield call(usersService.getFromIndex, {
а деструктуризация тут не поможет?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/services/db/index.js
> +  getByID = async (id) => {
а будет когда-то метод getByEmail?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/services/db/index.js
> +    return await db.transaction(this.tablespace, "readwrite").store.delete(id);
что будет если кинуть несуществующий id?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/services/db/UsersService.js
> +class UsersService extends DBService {
🧐

2021-02-09 15:17 UTC, oleksandrbazil commented on src/reducers/popupReducer.js
> +        ...state,
зачем подмешивать ?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/reducers/userReducer.js
> +        ...state,
зачем подмешивать стейт?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/reducers/usersReducer.js
> +  error: null,
почему null ?

2021-02-09 15:17 UTC, oleksandrbazil commented on src/reducers/usersReducer.js
> +export const GET_USERS = "GET_USERS";
почитай как лучше всего называть `action type`

2021-02-10 07:04 UTC, woohoo1607 commented on package.json
> +    "dayjs": "^1.10.4",
Это вместо moment.js установил, что бы работать с датами

2021-02-10 07:35 UTC, woohoo1607 commented on src/components/PopUp/index.js
> +import PopUpWindow from "../UI/PopUpWindow";
переименовал на Notification

2021-02-10 07:35 UTC, woohoo1607 commented on src/components/PopUp/index.js
> +      setTimeout(() => dispatch(closePopUp()), 6000);
ну это что бы он сам закрывался через время=)

2021-02-10 07:38 UTC, woohoo1607 commented on src/components/PopUp/index.js
> +  return <>{isOpen && <PopUpWindow msg={msg} variant={variant} />}</>;
я думаю нет

2021-02-10 07:38 UTC, woohoo1607 commented on src/components/PopUp/index.js
> +  const { isOpen, msg, variant } = useSelector(({ popup }) => popup);
ок

2021-02-10 07:42 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  unsavedData = null,
так легче будет сделать проверку есть ли несохраненные данные, чем если я туда пустой обьект запихну

2021-02-10 07:46 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +    const { slug } = steps[currentStepIndex + 1] || {};
оно перекинет на первый степ тогда=) 
П.С. добавил проверку if(currentSrepIndex)

2021-02-10 07:47 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +        {unsavedData && (
так тут не булево значение. unsavedData может быть или null если ничего нет, или обьектом если есть несохраненные данные

2021-02-10 07:50 UTC, woohoo1607 commented on src/components/UI/PopUpWindow/index.js
> +      <p>{msg}</p>
я подумаю над этим=)

2021-02-10 07:51 UTC, woohoo1607 commented on src/App.css
> +  --primary-bg-color: #5E97F3;
ну типа background color

2021-02-10 07:54 UTC, woohoo1607 commented on src/components/UserForms/ProfileForm.js
> +      (value) => dayjs().diff(dayjs(value), "years") >= 18
вынес в константу MIN_USER_AGE

2021-02-10 07:54 UTC, woohoo1607 commented on src/components/UserInformation/styles.css
> +.user-information-block > .user-information-title {
потому что у меня есть еще тек с таким классом, ему оно не нужно=)

2021-02-10 07:58 UTC, woohoo1607 commented on src/components/UsersTable/RowItem.js
> +  dayjs.extend(relativeTime);
добавляет для dayjs нужные мне методы (это по доке так)

2021-02-10 08:01 UTC, woohoo1607 commented on src/components/UsersTable/RowItem.js
> +      <TableCell>{`${dayjs(lastUpdate).fromNow(true)} ago`}</TableCell>
в lastUpdate дата, если будет undefined, то либа выведет - "a few seconds ago"

2021-02-10 08:03 UTC, woohoo1607 commented on src/components/UsersTable/index.js
> +          <TableHeadCell style={{ minWidth: "125px" }}>
та там проблемки с версткой потом вылезли=)

2021-02-10 08:05 UTC, woohoo1607 commented on src/components/UsersTable/index.js
> +        {users.map((item, i) => (
загуглил и нашел ответ=) Когда нету в обьектах уникальных свойств - к примеру id

2021-02-10 08:08 UTC, woohoo1607 commented on src/helpers/dataURItoBlob.js
> +  const byteString = atob(dataURI.split(",")[1]);
может=) Я просто нашел написаный конвертер и заюзал его=)

2021-02-10 08:09 UTC, woohoo1607 commented on src/helpers/dataURItoBlob.js
> +  const mimeString = dataURI.split(",")[0].split(":")[1].split(";")[0];
ответил выше=)

2021-02-10 08:09 UTC, woohoo1607 commented on src/helpers/dataURItoBlob.js
> +  const _ia = new Uint8Array(arrayBuffer);
такое было готовое решение=)

2021-02-10 08:11 UTC, woohoo1607 commented on src/icons/Spinner.svg
> +<!-- [ldio] generated by https://loading.io/ --></svg>
добавил, я просто во внутрь svg и не лазил

2021-02-10 08:19 UTC, woohoo1607 commented on src/helpers/localStorageHelper.js
> +export const getData = async (name) =>
в name строка, в data может быть строка или JSON строка, setData ничего не возвращает мне=)

2021-02-10 08:24 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +  const savePart = useCallback((data) => dispatch(addAccountData(data)), [
та да, перемудрил=) порефакторил

2021-02-10 08:24 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +  const createUser = useCallback((user) => dispatch(addUser(user)), [dispatch]);
убрал я его, он там не нужен

2021-02-10 08:26 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +    (async () => {
запрос на несохраненные данные при создании пользователя, если они есть

2021-02-10 08:26 UTC, woohoo1607 commented on src/reducers/actions.js
> +  delete newUser.allowedUnsubmittedStep;
что бы не мутировать обьект user=)

2021-02-10 08:28 UTC, woohoo1607 commented on src/reducers/popupReducer.js
> +  variant: "primary",
isOpen отвечает нужно ли отображать нам, msg (переименовал в message) хранит сообщение которое нужно отобразить, variant - это стилизация, ну может быть success и error, тогда бордер будет менятся

2021-02-10 08:29 UTC, woohoo1607 commented on src/services/db/index.js
> +  getByID = async (id) => {
ну у меня есть метод getFromIndex и там можно искать по любому индексу

2021-02-10 08:32 UTC, oleksandrbazil commented on package.json
> +    "dayjs": "^1.10.4",
так а момент в проекте остался :)

2021-02-10 08:33 UTC, woohoo1607 commented on src/sagas/userSaga.js
> +      const res = yield call(usersService.getFromIndex, {
это гениально =)

2021-02-10 08:34 UTC, woohoo1607 commented on src/services/db/index.js
> +    return await db.transaction(this.tablespace, "readwrite").store.delete(id);
вернет undefined. Я так понял что нужно для indexedDB добавить обработку ошибок?

2021-02-10 08:34 UTC, oleksandrbazil commented on src/components/PopUp/index.js
> +  return <>{isOpen && <PopUpWindow msg={msg} variant={variant} />}</>;
```js
return isOpen ? <PopUpWindow msg={msg} variant={variant} /> : null;
```

2021-02-10 08:34 UTC, woohoo1607 commented on src/services/db/UsersService.js
> +class UsersService extends DBService {
что смущает?=)

2021-02-10 08:35 UTC, woohoo1607 commented on src/reducers/userReducer.js
> +        ...state,
согласен, не имеет смысла, отрефакторил

2021-02-10 08:35 UTC, woohoo1607 commented on src/reducers/popupReducer.js
> +        ...state,
отрефакторил

2021-02-10 08:38 UTC, woohoo1607 commented on src/reducers/usersReducer.js
> +export const GET_USERS = "GET_USERS";
ок, поищу

2021-02-10 08:42 UTC, oleksandrbazil commented on src/App.css
> +  --primary-bg-color: #5E97F3;
а что будешь делать когда нужно будет установить `color` ?

2021-02-10 08:44 UTC, oleksandrbazil commented on src/components/UserForms/ProfileForm.js
> +      (value) => dayjs().diff(dayjs(value), "years") >= 18
вынеси проверку в отдельный метод который можно переиспользовать в другом месте что бы проверить прошел ли 21 год с даты до сегодня

2021-02-10 08:44 UTC, oleksandrbazil commented on src/components/UserInformation/styles.css
> +.user-information-block > .user-information-title {
а в чем между ними разница?

2021-02-10 08:45 UTC, oleksandrbazil commented on src/components/UsersTable/RowItem.js
> +  dayjs.extend(relativeTime);
почему она находиться в отдельно стоящем компоненте? 
что нужно будет делать когда эти методы понадобятся в другом компоненте?

2021-02-10 08:53 UTC, oleksandrbazil commented on src/helpers/dataURItoBlob.js
> +  const byteString = atob(dataURI.split(",")[1]);
как мне это понять?

2021-02-10 08:56 UTC, oleksandrbazil commented on src/reducers/popupReducer.js
> +  variant: "primary",
а зачем variant: "primary" засовывать в state?

2021-02-10 08:57 UTC, oleksandrbazil commented on src/services/db/index.js
> +  getByID = async (id) => {
а почему форма по индексу ищется? разве у тебя не по slug должна форма приходить?

2021-02-10 14:42 UTC, oleksandrbazil approved these changes
мердж, остальное посмотрю позже

2021-02-10 21:14 UTC, merged