feat: Add generate random users
woohoo1607/manager pull request #15
Opened 2021-02-11 07:31 UTC by woohoo1607

2021-02-11 19:36 UTC, oleksandrbazil requested changes

2021-02-11 19:36 UTC, oleksandrbazil commented on src/components/UserForms/AccountForm.js
> +      value && value instanceof Blob ? value.size <= MAX_PHOTO_SIZE : true
нужна ли первая проверка value?

2021-02-11 19:36 UTC, oleksandrbazil commented on src/helpers/generateAccount.js
> +import { SKILLS } from "../components/UserForms/skillsList";
почему вынес каждую константу в отдельный файл?

2021-02-11 19:36 UTC, oleksandrbazil commented on src/actions/userActions.js
> +  GENERATE_USERS,
а чем обусловлена реализация Generate Users с использованием Redux?

2021-02-11 20:52 UTC, woohoo1607 commented on src/components/UserForms/AccountForm.js
> +      value && value instanceof Blob ? value.size <= MAX_PHOTO_SIZE : true
Да, потому что если пользователь не загрузит фото, то ему не даст идти дальше, будет ошибка валидации

2021-02-11 20:54 UTC, woohoo1607 commented on src/helpers/generateAccount.js
> +import { SKILLS } from "../components/UserForms/skillsList";
Лучше что бы они в одном месте все были?

2021-02-11 20:56 UTC, woohoo1607 commented on src/actions/userActions.js
> +  GENERATE_USERS,
Кнока диспатчит екшен, и сага потом уже шлет запросы в базу и сразу обновляет стейт редакса где хранится список пользователей

2021-02-11 22:10 UTC, oleksandrbazil commented on src/actions/userActions.js
> +  GENERATE_USERS,
Redux и Redux сага ничего не должны знать про генерацию пользователей, перепиши так что бы это была отдельная функция которая создает список пользователей и потом засовывает их в Store

2021-02-11 22:13 UTC, oleksandrbazil commented on src/helpers/generateAccount.js
> +import { SKILLS } from "../components/UserForms/skillsList";
да, когда константы в отдельных файлах:
- при редактировании названия константы нужно менять название файла
- каждую константу нужно импортировать отдельно

2021-02-11 22:17 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +        <Button onClick={generateData}>Generate accounts</Button>
хотел написать что у тебя кнопка находиться не в том компоненте, а вижу что в целом страницы разбросаны. Пожалуйста, сгруппируй по сущности User 
pages/user/....
и убери  TemplatePage из pages это явно переиспользуемый компонент нежели страница

2021-02-12 07:07 UTC, woohoo1607 commented on src/helpers/generateAccount.js
> +import { SKILLS } from "../components/UserForms/skillsList";
вынес

2021-02-12 07:19 UTC, woohoo1607 commented on src/actions/userActions.js
> +  GENERATE_USERS,
переписал

2021-02-12 07:25 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +        <Button onClick={generateData}>Generate accounts</Button>
сделал

2021-02-12 13:01 UTC, oleksandrbazil commented on src/services/db/UsersService.js
> +  generateUsers = async (count) => {
let's use Promise / Promise.all

2021-02-15 12:19 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +          className="generate_button"
:(

2021-02-15 12:19 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +          disabled={isGenerate}
present continuous :) isGenerating

2021-02-15 12:19 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +        ) : null}
а зачем тут null ?

2021-02-15 12:19 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +  const generateUsers = () => setIsGenerate(true);
почему не используешь useState?

2021-02-15 12:19 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +              generateAccount().then((res) => usersService.add(res))
Напиши плз в чем преимущества и недостатки добавления пользователей:
- по одному
- всех сразу

2021-02-15 12:19 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +          dispatch(openNotification({ message, variant: "error" }));
а пулл реквест с openErrorNotification не в мастере(main)?

2021-02-15 12:19 UTC, oleksandrbazil commented on src/helpers/generateAccount.js
> +      phones: [`+38 ${faker.phone.phoneNumber().replace(/-/gi, " ")}`],
:D дважды пишешь одно и то же :)

2021-02-15 13:54 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +  const generateUsers = () => setIsGenerate(true);
использую, просто функцию написал generateUsers что бы ее на кнопку вешать, а не колбек делать

2021-02-15 13:55 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +        ) : null}
та просто проверку через тернарный оператор делал

2021-02-15 13:56 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +          dispatch(openNotification({ message, variant: "error" }));
к сожалению еще нет=)

2021-02-15 13:57 UTC, woohoo1607 commented on src/helpers/generateAccount.js
> +      phones: [`+38 ${faker.phone.phoneNumber().replace(/-/gi, " ")}`],
вынес

2021-02-15 14:00 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +              generateAccount().then((res) => usersService.add(res))
когда добавляем пользователя одного или несколько сразу, то таблица на время недоступна. Поэтому если мы добавляем много пользователей сразу и это занимает много времени, то долгое время другие не смогут получать с нее данные, но при этом мы один раз делаем запрос в БД. Ну а по одному когда добавляем то все с точностью, да наоборот=)

2021-02-15 14:00 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +          className="generate_button"
?

2021-02-15 16:19 UTC, oleksandrbazil approved these changes

2021-02-16 08:00 UTC, merged