refactor: Change the logic of saving temporary data
woohoo1607/manager pull request #17
Opened 2021-02-11 13:07 UTC by woohoo1607

2021-02-11 21:46 UTC, oleksandrbazil requested changes

2021-02-11 21:46 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +  const removeUnsavedData = () => dispatch(deleteTempUserData());
почему вынес в переменную?

2021-02-11 21:46 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +    fetchTempUserData();
React скорее всего будет ругаться, на то что нет зависимости. Как можно решить эту проблему?

2021-02-11 21:46 UTC, oleksandrbazil commented on src/reducers/userReducer.js
> +export const GET_TEMP_USER_DATA = "GET_TEMP_USER_DATA";
забавно, `userReducer` а внутри оперируешь понятием account/data/temp_data, может все-таки привести все названия к сущности?
может есть смысл отделить user от temp_data?

2021-02-11 21:46 UTC, oleksandrbazil commented on src/reducers/userReducer.js
> +      return {
почему подмешиваешь initialState?

2021-02-11 21:46 UTC, oleksandrbazil commented on src/sagas/userSaga.js
> +    yield put({ type: GET_TEMP_USER_DATA_SUCCESS, payload: res[0] || null });
а что будет если прилетит ошибка с сервера?

2021-02-11 21:46 UTC, oleksandrbazil commented on src/sagas/userSaga.js
> +    yield put(openNotification({ message, variant: "error" }));
1. почему Open, а не Send? 
2. а можно было сделать обертку openErrorNotification ? что бы не писать каждый раз `variant: "error"` ?

2021-02-11 21:46 UTC, oleksandrbazil commented on src/sagas/userSaga.js
> +  yield takeEvery(REMOVE_TEMP_USER_DATA, deleteTempUserDataSaga);
- REMOVE_TEMP_USER_DATA
- deleteTempUserDataSaga

пожалуйста, будь последовательным, выбери 1 слово `remove` или `delete` и используй повсеместно

2021-02-11 21:46 UTC, oleksandrbazil commented on src/services/db/UsersTempDataService.js
> +    super("temp");
что такое temp? как оно должно работать и как используется?

2021-02-11 21:46 UTC, oleksandrbazil commented on src/services/db/UsersTempDataService.js
> +    return await this.getByID(id);
второй запрос к БД? а почему бы не вернуть готового пользователя сразу в return для put/add?

2021-02-11 21:46 UTC, oleksandrbazil commented on src/services/db/UsersTempDataService.js
> +      id = await this.add(user);
не могу сохранить Account форму 
<img width="489" alt="1" src="https://user-images.githubusercontent.com/12004038/107702720-52e39080-6cc3-11eb-9bf1-cb5077db6f00.png">

2021-02-12 07:28 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +  const removeUnsavedData = () => dispatch(deleteTempUserData());
потому что я это функцию передаю в пропсах дальше

2021-02-12 07:28 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +    fetchTempUserData();
исправил

2021-02-12 07:31 UTC, woohoo1607 commented on src/sagas/userSaga.js
> +    yield put({ type: GET_TEMP_USER_DATA_SUCCESS, payload: res[0] || null });
откроется Notification с ошибкой

2021-02-12 07:41 UTC, woohoo1607 commented on src/sagas/userSaga.js
> +    yield put(openNotification({ message, variant: "error" }));
Сделал

2021-02-12 07:42 UTC, woohoo1607 commented on src/sagas/userSaga.js
> +  yield takeEvery(REMOVE_TEMP_USER_DATA, deleteTempUserDataSaga);
хорошо

2021-02-12 07:44 UTC, woohoo1607 commented on src/services/db/UsersTempDataService.js
> +    super("temp");
это название таблицы для хранения данных. При отправке запросов в indexedDB оно потом его подставляет

2021-02-12 07:45 UTC, woohoo1607 commented on src/services/db/UsersTempDataService.js
> +    return await this.getByID(id);
прийдется в методах put и add делать второй запрос, потому что они возвращаю ID. А так я делаю второй запрос только если мне действительно нужно взять обновленные данные.

2021-02-12 07:46 UTC, woohoo1607 commented on src/services/db/UsersTempDataService.js
> +      id = await this.add(user);
надо наверное удалить базу indexedDB и что бы она заново создалась

2021-02-12 07:50 UTC, woohoo1607 commented on src/reducers/userReducer.js
> +export const GET_TEMP_USER_DATA = "GET_TEMP_USER_DATA";
просто temp_data отосится к юзеру. Может названия стоит более подходящии придумать

2021-02-12 13:29 UTC, oleksandrbazil commented on src/reducers/userReducer.js
> +export const GET_TEMP_USER_DATA = "GET_TEMP_USER_DATA";
попробуй перименовать с более понятными словами
для саг используй название TRIGGER или SAGA...

2021-02-12 14:03 UTC, oleksandrbazil commented on src/services/db/UsersTempDataService.js
> +    return await this.getByID(id);
сделай плз это поведение для DBService по умолчанию, что бы не писать каждый раз для новой сущности

2021-02-12 14:04 UTC, oleksandrbazil commented on src/services/db/UsersTempDataService.js
> +      id = await this.add(user);
сделай так что бы обновлялись версии БД

2021-02-15 14:17 UTC, oleksandrbazil commented on src/actions/userFormActions.js
> +    type: TRIGGER_CHECK_USER_FORM,
а что имеется ввиду под CHECK_USER_FORM?

2021-02-15 14:17 UTC, oleksandrbazil commented on src/actions/userFormActions.js
> +  if (Object.prototype.hasOwnProperty.call(userData, "phones")) {
можно ли обойтись деструктуризацией?

2021-02-15 14:17 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +  removeUserForm,
а в чем принципиальное отличие от clearUserFormState ?

2021-02-15 14:17 UTC, oleksandrbazil commented on src/reducers/userFormReducer.js
> +export const GET_USER_FORM = "GET_USER_DATA";
обычно пишут через префикс
```suggestion
export const USER_GET_FORM = "USER/GET_FORM";
```
это для саг? почему тут GET?

2021-02-15 14:17 UTC, oleksandrbazil commented on src/reducers/userFormReducer.js
> +    allowedUnsubmittedStep: 0,
я помню что мы ориентируемся на slug, что по сути строка, а тут уже смотрим на индексы. Почему так?

2021-02-15 14:17 UTC, oleksandrbazil commented on src/sagas/usersSagas.js
> +    yield put({ type: IS_LOADING, payload: false });
а можно ли вынести после блока try/catch?

2021-02-15 14:17 UTC, oleksandrbazil commented on src/services/db/UserFormService.js
> +      return await this.add(user);
можно ли написать короче?

2021-02-15 14:17 UTC, oleksandrbazil commented on src/services/db/UsersService.js
> +    const foundedUserByEmail = await this.checkEmail(email);
а почему нельзя сразу поискать пользователя по email?

2021-02-15 14:17 UTC, oleksandrbazil commented on src/services/db/index.js
> +      if (oldVersion < 1) {
это миграции?
что тут будет когда миграций будет больше 10?

2021-02-15 14:25 UTC, woohoo1607 commented on src/actions/userFormActions.js
> +    type: TRIGGER_CHECK_USER_FORM,
проверить есть ли у нас данные, и если есть то потом ставим `isAvailable=true` и выводим сообщение что можно загрузить ранее введенные данные

2021-02-15 14:32 UTC, woohoo1607 commented on src/actions/userFormActions.js
> +  if (Object.prototype.hasOwnProperty.call(userData, "phones")) {
можно, переписал

2021-02-15 14:33 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +  removeUserForm,
`clearUserFormState` - очищает стейт userForm
`removeUserForm` - удаляет данные из БД и соответсвенно тоже очищает стейт

2021-02-15 14:36 UTC, woohoo1607 commented on src/reducers/userFormReducer.js
> +export const GET_USER_FORM = "GET_USER_DATA";
`GET_USER_FORM` это когда сага успешно получит данные, диспатчит это екшн и данные залетают в стейт. Для самой саги экшн `TRIGGER_GET_USER_FORM`

2021-02-15 14:38 UTC, woohoo1607 commented on src/reducers/userFormReducer.js
> +    allowedUnsubmittedStep: 0,
там при каждом действии нужно искать индекс этиг слагов, когда переключаешься между вкладками, так получается проще

2021-02-15 14:40 UTC, woohoo1607 commented on src/sagas/usersSagas.js
> +    yield put({ type: IS_LOADING, payload: false });
можно=)

2021-02-15 14:46 UTC, woohoo1607 commented on src/services/db/UserFormService.js
> +      return await this.add(user);
сделал

2021-02-15 14:47 UTC, woohoo1607 commented on src/services/db/UsersService.js
> +    const foundedUserByEmail = await this.checkEmail(email);
оно ищет только по одному индексу

2021-02-15 14:50 UTC, woohoo1607 commented on src/services/db/index.js
> +      if (oldVersion < 1) {
там логику еще больше писать прийдется=) Смотря какая версия у пользователя, и какая последня версия, нужно будет писать разные функции. Ну я так понял

2021-02-15 15:00 UTC, woohoo1607 commented on src/services/db/index.js
> +      if (oldVersion < 1) {
В последнем коммите переписал

2021-02-15 15:40 UTC, oleksandrbazil approved these changes

2021-02-15 21:53 UTC, merged