Feat/pagination
woohoo1607/manager pull request #19
Opened 2021-02-11 15:55 UTC by woohoo1607

2021-02-11 22:54 UTC, oleksandrbazil requested changes

2021-02-11 22:54 UTC, oleksandrbazil commented on package.json
> +    "react-paginate": "^7.0.0",
в описании экстра задания не написано что нельзя использовать сторонние пакеты, но как я понимаю эту задачу нужно делать без стороннего кода что бы я мог понять что ты учтешь в этой задаче а что упустишь.
Я погляжу этот ПР, но в конце нужно будет отдельным PR попробовать реализовать эту задачу самостоятельно

2021-02-11 22:54 UTC, oleksandrbazil commented on src/actions/userActions.js
> +    page,
зачем page в Redux?

2021-02-11 22:54 UTC, oleksandrbazil commented on src/components/Paginator/styles.css
> +.pagination__link, .pagination__page {
а в чем тогда отличие `pagination__link` и `pagination__page` ?

2021-02-11 22:54 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +  const query = useMemo(() => new URLSearchParams(search), [search]);
а зачем нам переменная `query`? можем без нее обойтись?

2021-02-11 22:54 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +    const page = query.get("page") > 0 ? query.get("page") : 1;
2 раза пишешь одно и то же

2021-02-11 22:54 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +    fetchUsers({ page });
запрос к БД каждый раз когда пользователь переходит на другую страницу?

2021-02-11 22:54 UTC, oleksandrbazil commented on src/services/db/UsersService.js
> +      pages: Math.round(allUsers.length / count),
почему это нужно хранить в Redux?

2021-02-11 22:54 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +    const page = query.get("page") > 0 ? query.get("page") : 1;
Ситуация:
- есть 3 страницы с пользователями (на последней странице 1 профиль)
-  менеджер скидывает ссылку на последнюю страницу своему коллеге http://localhost:3000/?page=3 
- в это время кто-то удаляет профиль последнего профиля на третей странице 
- после чего пользователь открывает ссылку
**Вопрос**: что увидит пользователь когда откроет не существующую страницу?

2021-02-11 22:54 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +        {pages ? (
получается когда у нас будет 4 пользователя - мы не будем показывать пагинацию, а когда будет 5 - будем 👍

2021-02-12 08:21 UTC, woohoo1607 commented on src/components/Paginator/styles.css
> +.pagination__link, .pagination__page {
`pagination__link` - это кнопки Next и Previous
`pagination__page` - это кнопки 1,2,3,.....

2021-02-12 08:24 UTC, woohoo1607 commented on src/actions/userActions.js
> +    page,
я диспатчу action GET_USERS и передаю параметр page что бы с базы вытянуть не всех пользователей а только часть

2021-02-12 08:24 UTC, woohoo1607 commented on package.json
> +    "react-paginate": "^7.0.0",
хорошо

2021-02-12 08:25 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +    fetchUsers({ page });
ну да, а что это плохо?=)

2021-02-12 08:27 UTC, woohoo1607 commented on src/services/db/UsersService.js
> +      pages: Math.round(allUsers.length / count),
ну сервер возвращает количество страниц на которые помещаются все юзеры, как бы нужные данные. П.С. а куда мне их девать если не в редакс?

2021-02-12 08:30 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +        {pages ? (
исправил что бы сервак возвращал pages = 1 когда мало пользователей=)

2021-02-12 09:08 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +    const page = query.get("page") > 0 ? query.get("page") : 1;
переписал

2021-02-12 09:08 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +  const query = useMemo(() => new URLSearchParams(search), [search]);
ну разве что вручную парсить URL

2021-02-12 09:09 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +    const page = query.get("page") > 0 ? query.get("page") : 1;
ну тогда пользователь увидет заглушку для создания пользователя.
П.С. переписал логику

2021-02-12 14:25 UTC, oleksandrbazil commented on src/components/Paginator/styles.css
> +.pagination__link, .pagination__page {
pagination_item
pagination_item--link

2021-02-16 12:22 UTC, oleksandrbazil commented on src/components/Paginator/index.js
> +        if (queryPage <= 0 || queryPage > pages) {
тут слишком много вложенности if:
- 1 было бы идеально
- 2 допустимо
- 3 много

2021-02-16 12:22 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +  const query = useMemo(() => new URLSearchParams(search), [search]);
кто-то мне обещал переиспользовать эту переменную -  не вижу где

2021-02-16 12:22 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +          users={users.slice(
почему логика обработки пользователей в рендере?

2021-02-16 12:22 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +        {!users.length && !(isLoading || isGenerating) ? (
почему тут нужна проверка isLoading || isGenerating?
есть ли повторения этой проверки?

2021-02-16 12:22 UTC, oleksandrbazil commented on src/services/db/UsersService.js
> +      pages: Math.round(allUsers.length / count) || 1,
мы же говорили о том что не стоит считать pages на сервере?

2021-02-16 12:24 UTC, oleksandrbazil commented on src/components/Paginator/index.js
> +        if (queryPage <= 0 || queryPage > pages) {
а зачем тебе проверка `Number.isInteger(+queryPage)`?

2021-02-16 12:34 UTC, woohoo1607 commented on src/services/db/UsersService.js
> +      pages: Math.round(allUsers.length / count) || 1,
забыл удалить, этот кусок не используется

2021-02-16 12:42 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +        {!users.length && !(isLoading || isGenerating) ? (
обьеденил

2021-02-16 12:43 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +  const query = useMemo(() => new URLSearchParams(search), [search]);
та я сейчас с поиском борюсь, там она и используется еще раз

2021-02-16 12:54 UTC, woohoo1607 commented on src/components/Paginator/index.js
> +        if (queryPage <= 0 || queryPage > pages) {
уменьшил до 2=)

2021-02-16 14:28 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +          users={users.slice(
вынес в стейт

2021-02-16 15:23 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +            offset * NUMBER_OF_USERS_TO_SHOW,
может offset быть равен 0? если да, то как этот код будет работать?

2021-02-16 15:50 UTC, oleksandrbazil commented on src/components/Paginator/index.js
> +      if (!Number.isInteger(+queryPage) || (queryPage === 1 && offset)) {
можно ли здесь использовать else if?

2021-02-16 15:50 UTC, oleksandrbazil commented on src/components/Paginator/index.js
> +      if (!Number.isInteger(+queryPage) || (queryPage === 1 && offset)) {
что делает проверка `Number.isInteger(+queryPage)` ?

2021-02-16 15:50 UTC, oleksandrbazil commented on src/pages/HomePage/UserGenerator.js
> +  for (let i = 0; i < count; i++) {
почему сделал через `for`?

2021-02-16 15:50 UTC, oleksandrbazil commented on src/pages/HomePage/UserGenerator.js
> +        .then((res) => usersService.clearAll().then(() => res))
res это result или response? или resources?...

2021-02-16 15:50 UTC, oleksandrbazil commented on src/pages/HomePage/UserGenerator.js
> +  useEffect(() => {
1) попробуй переписать на Redux/Saga action (без useEffect)
2) переименуй `addMany` на `import`

2021-02-16 15:50 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +        offset * NUMBER_OF_USERS_TO_SHOW,
https://github.com/woohoo1607/manager/pull/19#discussion_r576906777

2021-02-16 21:45 UTC, oleksandrbazil commented
пожалуйста, стилизируй пагинацию  в цветовой схеме проекта

2021-02-17 07:00 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +            offset * NUMBER_OF_USERS_TO_SHOW,
да может быть равным 0, тогда будет создаваться массив от 0-го элемента.

2021-02-17 07:01 UTC, woohoo1607 commented on src/pages/HomePage/index.js
> +        offset * NUMBER_OF_USERS_TO_SHOW,
да может быть равным 0, тогда будет создаваться массив от 0-го элемента.

2021-02-17 07:02 UTC, woohoo1607 commented on src/components/Paginator/index.js
> +      if (!Number.isInteger(+queryPage) || (queryPage === 1 && offset)) {
ага, подправил=)

2021-02-17 07:02 UTC, woohoo1607 commented on src/components/Paginator/index.js
> +      if (!Number.isInteger(+queryPage) || (queryPage === 1 && offset)) {
проверяет, что бы в queryPage было целое число

2021-02-17 07:03 UTC, woohoo1607 commented on src/pages/HomePage/UserGenerator.js
> +        .then((res) => usersService.clearAll().then(() => res))
result
Дописал

2021-02-17 07:10 UTC, woohoo1607 commented on src/pages/HomePage/UserGenerator.js
> +  for (let i = 0; i < count; i++) {
нашел способ уменьшить код=)

2021-02-17 07:56 UTC, woohoo1607 commented on src/pages/HomePage/UserGenerator.js
> +  useEffect(() => {
сделал

2021-02-17 12:32 UTC, oleksandrbazil commented on src/pages/HomePage/index.js
> +          <Paginator
а давай сделаем отображение пагинации только когда пользователей больше одной страници - это будет лучше с точки зрения UX

2021-02-17 12:32 UTC, oleksandrbazil commented on src/actions/userActions.js
> +export const setIsLoading = (payload = false) => ({
не используется?

2021-02-17 12:33 UTC, oleksandrbazil approved these changes
как поправишь - мердж

2021-02-17 12:35 UTC, oleksandrbazil commented on src/components/Paginator/styles.css
> +    color: #9BB0CB;
переменная?

2021-02-17 13:03 UTC, merged