Feat/add user step 1
woohoo1607/manager pull request #2
Opened 2021-01-21 15:27 UTC by woohoo1607

2021-01-21 16:17 UTC, oleksandrbazil requested changes

2021-01-21 16:17 UTC, oleksandrbazil commented on src/App.css
> +  color: #FFFFFF;
белый текст на белом фоне? :)

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/Button/index.js
> +      type={type}
а что будешь делать если нужно будет добавить еще атрибуты? например disabled или data-test-id ?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/Button/index.js
> +const Button = ({ color = "primary", type, title, onClick }) => {
primary - это не цвет, попробуй найти более удачное название для этого

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/Button/index.js
> +const Button = ({ color = "primary", type, title, onClick }) => {
а почему для onClick не установлено значение по умолчанию?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/ButtonHeaderForm/index.js
> +const ButtonHeaderForm = ({ children, onClick, type }) => {
а чем этот компонент принципиально отличается от Button Component?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/Header/index.js
> +  const isAddUserFlow = pathname.split("/")[2] === "new";
- `pathname` может быть undefined?
- что произойдет если `pathname` будет underfined?
- useHistory() может не иметь  свойство `location`?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/Input/index.js
> +  const isError = touched[field.name] && errors[field.name];
ооо, приехали :) - добавляем логику от формика в Input
Это плохой подход, потому что если завтра мы удалим формик из проекта, у нас будут зависимые Input
Смотри:
- Button, Input, Select ... etc -- это все относиться к UI и отвечает только за отображение: цвет, форма, анимация и прочее
- formik - это библиотека и она использует логику обработку полей

Как думаешь что нужно сделать? как это правильно реализовать?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/UserForm/AccountForm.js
> +  };
а как можно написать короче?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/UserForm/AccountForm.js
> +const AccountForm = ({ addData, username, password, avatar }) => {
нам нужно что бы входящие параметры были undefined?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/Button/index.js
> +const Button = ({ color = "primary", type, title, onClick }) => {
нужно ли устанавливать type по умолчанию?
какой тип кнопки используется по умолчанию?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/UserForm/index.js
> +            </li>
обрати внимание на этот кусок кода, подумай и скажи мне, пожалуйста, как можно сделать этот же кусок по другому?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/UserForm/index.js
> +  const { username, password, avatar } = user;
надо ли нам переменная user?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/components/UserForm/styles.css
> +    background: url("../../icons/list-of-users.svg") 50% 105% no-repeat;
посмотри макет и скажи почему ты решил реализовать AvatarContainer таким образом?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/containers/UserFormContainer/index.js
> +    console.log(step);
как так?)

2021-01-21 16:17 UTC, oleksandrbazil commented on src/containers/UserFormContainer/index.js
> +const UserFormContainer = () => {
почему в папке Containers? И что именно имеется ввиду под UserFormContainer?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/containers/UserFormContainer/actionTypes.js
> +export const ADD_PROFILE_DATA = "ADD_PROFILE_DATA";
зачем добавлял actionType для форм которые еще не сделаны? удалять не надо, просто интересно

2021-01-21 16:17 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +  const title = "Adding new user";
почему в переменной?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/pages/TemplatePage/index.js
> +import Index from "../../components/Header";
что такое Index?

2021-01-21 16:17 UTC, oleksandrbazil commented on src/routes/index.js
> +      <Route exact path="/" render={(props) => <TemplatePage {...props} />} />
будет легче читать если написание у всех компонентов будет похожим

2021-01-22 07:02 UTC, woohoo1607 commented on src/App.css
> +  color: #FFFFFF;
сделал черный=)

2021-01-22 07:03 UTC, woohoo1607 commented on src/components/Button/index.js
> +      type={type}
нужно прокинуть оставшиеся пропсы если вдруг прийдут?

2021-01-22 07:07 UTC, woohoo1607 commented on src/components/Button/index.js
> +const Button = ({ color = "primary", type, title, onClick }) => {
btnView подойдет?=)

2021-01-22 07:09 UTC, woohoo1607 commented on src/components/Button/index.js
> +const Button = ({ color = "primary", type, title, onClick }) => {
ожидается что это обязательный аргумент=)
а что ему можно по умолчанию задать?

2021-01-22 07:11 UTC, woohoo1607 commented on src/components/ButtonHeaderForm/index.js
> +const ButtonHeaderForm = ({ children, onClick, type }) => {
только стилями впринципе, подумаю как можно их объединить

2021-01-22 07:20 UTC, woohoo1607 commented on src/components/Header/index.js
> +  const isAddUserFlow = pathname.split("/")[2] === "new";
`const { pathname } = useHistory()?.location;
  const isAddUserFlow = pathname ? pathname.split("/")[2] === "new" : false;`

переписал вот так

2021-01-22 07:25 UTC, woohoo1607 commented on src/components/UserForm/AccountForm.js
> +  };
`const submit = (values) => addData(values);`

2021-01-22 07:26 UTC, woohoo1607 commented on src/components/UserForm/AccountForm.js
> +const AccountForm = ({ addData, username, password, avatar }) => {
нужно задать значения по умолчанию?

2021-01-22 07:27 UTC, woohoo1607 commented on src/components/Button/index.js
> +const Button = ({ color = "primary", type, title, onClick }) => {
по умолчанию type='button', добавил.

2021-01-22 07:30 UTC, woohoo1607 commented on src/components/UserForm/index.js
> +            </li>
Вынести в отдельный компонент которому передавать список в виде масива, и он будет это все мапить и рендерить

2021-01-22 07:37 UTC, woohoo1607 commented on src/components/UserForm/index.js
> +  const { username, password, avatar } = user;
ну в ней все данные о пользователе будут, почему нет?=)

2021-01-22 07:40 UTC, woohoo1607 commented on src/components/UserForm/styles.css
> +    background: url("../../icons/list-of-users.svg") 50% 105% no-repeat;
ну в бекграунде всегда будет такой фон, а если будет фото, то оно сверху ляжет. или это плохая идея и нужно просто в контейнер запихнуть <img> и проверять пришел аватар или нет, и уже выбирать что туда ставить,

2021-01-22 07:41 UTC, woohoo1607 commented on src/containers/UserFormContainer/index.js
> +    console.log(step);
та это я тестил и думал над вариантами перехода к следующему шагу =)

2021-01-22 07:43 UTC, woohoo1607 commented on src/containers/UserFormContainer/index.js
> +const UserFormContainer = () => {
ну тут будут делаться запросы к базе, что бы получить инфу о пользователе если она будет. Это будет нужно для редактирования пользователя, поскольку там такая же форма, и потом для фичи что бы продлолжыть заполнять информацию о пользователе если до конца форму не заполнил.

2021-01-22 07:43 UTC, woohoo1607 commented on src/containers/UserFormContainer/actionTypes.js
> +export const ADD_PROFILE_DATA = "ADD_PROFILE_DATA";
та это типа наперед=) ну я понял что наперед делать это не очень хорошо, все нужно делать постепенно=)

2021-01-22 07:45 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +  const title = "Adding new user";
ну вдруг название длинное, тогда в компоненту прийдется передавать длинную строку, поэтому решил сюда вынести.  Не нужно так делать?=)

2021-01-22 07:46 UTC, woohoo1607 commented on src/pages/TemplatePage/index.js
> +import Index from "../../components/Header";
то я переименовывал файлы и не заметил что ИДЕ исправила и здесь. Исправил на Header

2021-01-22 07:48 UTC, woohoo1607 commented on src/routes/index.js
> +      <Route exact path="/" render={(props) => <TemplatePage {...props} />} />
это в плане что некоторые роуты в одну строчку записаны, а некоторые в несколько? Если да то это IDE сама переносит если длинные строки=)

2021-01-22 12:48 UTC, oleksandrbazil requested changes

2021-01-22 12:48 UTC, oleksandrbazil commented on src/components/Button/index.js
> +      type={type}
похоже на правду, а зачем тогда явно передаешь `type` и `onclick`?

2021-01-22 12:48 UTC, oleksandrbazil commented on src/components/Button/styles.css
> +}
no new line :/

2021-01-22 12:48 UTC, oleksandrbazil commented on src/components/Header/index.js
> +  const isAddUserFlow = pathname ? pathname.split("/")[2] === "new" : false;
скажи, пожалуйста, какое значение pathname достаточно что бы сроботал этот тернарный оператор?
```
pathname ? pathname.split("/")[2] === "new" : false;
```

2021-01-22 12:48 UTC, oleksandrbazil commented on src/components/Header/index.js
> +  const { pathname } = useHistory()?.location;
синтаксис уже поддерживается ?

2021-01-22 12:48 UTC, oleksandrbazil commented on src/components/Input/index.js
> +      {isError && <p className="input-error">{errMsg}</p>}
а мы можем обойтись наличием только errMsg переменной?

2021-01-22 12:48 UTC, oleksandrbazil commented on src/components/UserForm/AccountForm.js
> +          <Field name="password">
тебе не кажется что блоки `<div className="account-form-input">...</div>` похожи между собой?

2021-01-22 12:48 UTC, oleksandrbazil commented on src/components/UserForm/AccountForm.js
> +          <Button title="Forward" btnView="primary" type="submit" />
а нам обязательно передавать параметр `btnView`?

2021-01-22 12:48 UTC, oleksandrbazil commented on src/components/UserForm/index.js
> +const list = [
вот так лучше, однако 
- название list не самое удачное - у него слишком обширное значение, лучше писать что-то конкретное
- обязательно ли передавать число шага?

2021-01-22 12:51 UTC, oleksandrbazil commented on src/components/Button/index.js
> +const Button = ({ color = "primary", type, title, onClick }) => {
пускай пока что будет так, дальше будет видно

2021-01-22 12:55 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +  const title = "Adding new user";
на сейчас смысла в переменной нет, по этому можно передать сразу текст, а это приводит к тому что мы можем написать NewUserPage в коротком синтаксе

2021-01-22 13:01 UTC, oleksandrbazil commented on src/components/Button/index.js
> +const Button = ({ color = "primary", type, title, onClick }) => {
не вижу что бы type был button по умолчанию, может глючит гит?
https://www.w3schools.com/jsref/prop_pushbutton_type.asp
посмотри что пишут про дефолтные значения

2021-01-22 16:03 UTC, oleksandrbazil commented on src/components/UserForm/styles.css
> +    background: url("../../icons/list-of-users.svg") 50% 105% no-repeat;
окей: тогда попозже вернемся к нему

2021-01-22 16:05 UTC, oleksandrbazil commented on src/routes/index.js
> +      <Route exact path="/" render={(props) => <TemplatePage {...props} />} />
понимаю, по этому подсказываю что когда такое случается, лучше переносить и другие элементы в этом блоке кода если они после этого будут читаться легче

2021-01-22 16:14 UTC, oleksandrbazil requested changes
Посмотри плз на комменты

2021-01-22 16:14 UTC, oleksandrbazil commented on src/components/StepWizard/AccountForm.js
> +            isError={meta.touched && Boolean(meta.error)}
можно ведь деструктуризировать touched error ?)
а почему передаешь onChange && onBlur функции?
можно ли передать все параметры без обявления прямо вниз дочернему компоненту? или там есть что-то что нельзя передавать?

2021-01-22 16:14 UTC, oleksandrbazil commented on src/components/StepWizard/AccountForm.js
> +      {rightItems.map((item, i) => (
почему rightItems? как по мне это больше похоже на AccountFormFields

Как считаешь будет лучше их назвать что бы передать суть переменной?

2021-01-25 07:10 UTC, woohoo1607 commented on src/components/StepWizard/AccountForm.js
> +      {rightItems.map((item, i) => (
У меня в форма поделена на 2 части, контент который слева и который справа, поэтому такое название и придумал=)) Что бы суть более подробно передать можно тогда дать название AccountFormRigthFields?

2021-01-25 07:21 UTC, woohoo1607 commented on src/components/StepWizard/AccountForm.js
> +            isError={meta.touched && Boolean(meta.error)}
onChange, onBlur, name и value явно теперь не передаю, исправил для следующего пулреквеста, потому что я этот кусок вынес в отдельный файл. Touched и error деструктуризировал=)

2021-01-25 07:56 UTC, woohoo1607 commented on src/components/Button/index.js
> +const Button = ({ color = "primary", type, title, onClick }) => {
глянул есть там дефолтное значение у меня:
https://github.com/woohoo1607/manager/blob/feat/add-user/src/components/Button/index.js

2021-01-25 07:57 UTC, woohoo1607 commented on src/components/UserForm/index.js
> +  const { username, password, avatar } = user;
Ну впринципе я могу в каждый шаг прокидывать данные о юзере целиком и брать только что нужно, но так правильно если компонент будет знать больше чем нужно?=)

2021-01-25 07:58 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +  const title = "Adding new user";
исправлено

2021-01-25 07:59 UTC, woohoo1607 commented on src/routes/index.js
> +      <Route exact path="/" render={(props) => <TemplatePage {...props} />} />
ок

2021-01-25 08:02 UTC, woohoo1607 commented on src/components/Header/index.js
> +  const isAddUserFlow = pathname ? pathname.split("/")[2] === "new" : false;
отличное от нуля, false, undefined, null, пустой строки

2021-01-25 08:03 UTC, woohoo1607 commented on src/components/Header/index.js
> +  const { pathname } = useHistory()?.location;
вроде да, я такое юзал вроде в прошлом году=)

2021-01-25 08:05 UTC, woohoo1607 commented on src/components/Input/index.js
> +      {isError && <p className="input-error">{errMsg}</p>}
нет, не получится, тогда будет сообщение выскакивать на всех инпутах сразу, даже на которые еще не переходили

2021-01-25 08:05 UTC, woohoo1607 commented on src/components/UserForm/AccountForm.js
> +          <Field name="password">
я подправил, только сейсас не скажу в каком коммите, надо найти=)

2021-01-25 08:05 UTC, woohoo1607 commented on src/components/UserForm/AccountForm.js
> +          <Button title="Forward" btnView="primary" type="submit" />
если primary то нет=)

2021-01-25 08:09 UTC, woohoo1607 commented on src/components/UserForm/index.js
> +const list = [
число шага не передаю уже, переименовал в stepList

2021-01-25 08:10 UTC, woohoo1607 commented on src/components/Button/index.js
> +      type={type}
ну в тайпе у меня там дефолтное значение задается

2021-01-25 08:54 UTC, oleksandrbazil commented on src/components/Header/index.js
> +  const isAddUserFlow = pathname ? pathname.split("/")[2] === "new" : false;
конкретно в этом случае так прокатит, но будь аккуратней с типами данных, в другом случае это может выдать ошибку и у тебя не будет работать приложение совсем

2021-01-25 09:02 UTC, oleksandrbazil commented on src/components/Input/index.js
> +      {isError && <p className="input-error">{errMsg}</p>}
:) думаю получиться, дестуктуризируй для начала параметры:
src/components/StepWizard/AccountForm.js:34

2021-01-25 09:09 UTC, oleksandrbazil commented on src/components/StepWizard/AccountForm.js
> +      {rightItems.map((item, i) => (
оставляй как есть, сделаешь вторую форму и я поясню почему такое решение не самое удачное :)

2021-01-25 09:18 UTC, oleksandrbazil approved these changes
мердж

2021-01-25 11:47 UTC, merged