Refactor/bug fix
woohoo1607/manager pull request #20
Opened 2021-02-17 13:11 UTC by woohoo1607

2021-02-17 13:56 UTC, oleksandrbazil requested changes

2021-02-17 13:56 UTC, oleksandrbazil commented on src/actions/notificationActions.js
> +export const showNotification = ({ message = "", variant = "success" }) => {
по умолчанию у тебя varaint Primary. тогда и добавь тут primary
а рядом сделай обертку для showSuccessNotification

2021-02-17 13:56 UTC, oleksandrbazil commented on src/components/SelectInput/index.js
> +      return options.filter((option) => value?.indexOf(option.value) >= 0);
мы же договаривались не использовать `?.`

2021-02-17 13:56 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const slug = data.slug ? data.slug : firstStepSlug;
зачем использовать тернарный оператор? здесь есть какое-то условие?

2021-02-17 13:56 UTC, oleksandrbazil commented on src/components/UserForms/FormikBody.js
> +const FormikBody = ({
может это должно лежать в UI папке?

2021-02-17 13:56 UTC, oleksandrbazil commented on src/components/UserForms/styles.css
> +    position: absolute !important;
зачем тут important?

2021-02-17 13:56 UTC, oleksandrbazil commented on src/components/UsersTable/styles.css
> +    vertical-align: middle;
тут можно обойтись без класса для кнопок, 
посмотри спецификацию и в частности **Applies to:**  для свойства `vertical-align`
https://www.w3.org/TR/CSS21/visudet.html#propdef-vertical-align

2021-02-17 13:56 UTC, oleksandrbazil commented on src/pages/User/NewUserPage/index.js
> +    dispatch(getUserForm({ meta: { redirect: push, path: "/users/new/" } }));
зачем нам слэш в конце? :)

2021-02-17 13:56 UTC, oleksandrbazil commented on src/reducers/userFormReducer.js
> +    fieldName: "",
а как это будет работать если back передаст нам 2 поля?

2021-02-17 13:56 UTC, oleksandrbazil commented on src/routes/index.js
> +      <Route exact path="/" component={HomePage} />
другое дело 👍

2021-02-17 13:56 UTC, oleksandrbazil commented on src/sagas/userFormSaga.js
> +      yield put({ type: UPDATE_USER_FORM, payload: res[0] || null });
а почему мы передаем payload = null?
это же сломает объект, не так ли?

2021-02-17 13:56 UTC, oleksandrbazil commented on src/sagas/userFormSaga.js
> +      yield call(redirect, `${path}${slug}`);
похоже тут где-то потерялся "/" между path и slug

2021-02-17 15:39 UTC, woohoo1607 commented on src/actions/notificationActions.js
> +export const showNotification = ({ message = "", variant = "success" }) => {
сделал

2021-02-17 15:51 UTC, woohoo1607 commented on src/components/SelectInput/index.js
> +      return options.filter((option) => value?.indexOf(option.value) >= 0);
убрал

2021-02-17 15:52 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const slug = data.slug ? data.slug : firstStepSlug;
Если slug - пустая строка, то присвоить ему значение первого слага

2021-02-17 15:53 UTC, woohoo1607 commented on src/components/UserForms/FormikBody.js
> +const FormikBody = ({
та не, оно относится конкретно к UsersForm, здесь значения вытягиваются из стейта

2021-02-17 15:56 UTC, woohoo1607 commented on src/sagas/userFormSaga.js
> +      yield put({ type: UPDATE_USER_FORM, payload: res[0] || null });
забыл убрать

2021-02-17 16:30 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const slug = data.slug ? data.slug : firstStepSlug;
а можно обойтись логическим оператором?

2021-02-17 16:33 UTC, oleksandrbazil commented on src/actions/notificationActions.js
> +export const showSuccessNotification = ({ message = "" }) => {
DRY ^_^
ты же можешь внутри функции вызвать другую функцию и передать туда параметры? :)

2021-02-18 07:07 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const slug = data.slug ? data.slug : firstStepSlug;
точно=)

2021-02-18 07:08 UTC, woohoo1607 commented on src/components/UserForms/styles.css
> +    position: absolute !important;
исправил

2021-02-18 07:09 UTC, woohoo1607 commented on src/pages/User/NewUserPage/index.js
> +    dispatch(getUserForm({ meta: { redirect: push, path: "/users/new/" } }));
что бы потом просто слаг подставить=)

2021-02-18 07:09 UTC, woohoo1607 commented on src/sagas/userFormSaga.js
> +      yield call(redirect, `${path}${slug}`);
слеш уже в path=)
Переписал как ты сказал, так нагляднее и лучше будет=)

2021-02-18 07:18 UTC, woohoo1607 commented on src/components/UsersTable/styles.css
> +    vertical-align: middle;
исправил

2021-02-18 07:28 UTC, woohoo1607 commented on src/reducers/userFormReducer.js
> +    fieldName: "",
исправил

2021-02-18 07:31 UTC, woohoo1607 commented on src/actions/notificationActions.js
> +export const showSuccessNotification = ({ message = "" }) => {
не совсем понял про что ты говоришь=)

2021-02-18 09:33 UTC, oleksandrbazil approved these changes

2021-02-18 09:33 UTC, oleksandrbazil commented on src/actions/notificationActions.js
> +export const showSuccessNotification = ({ message = "" }) => {
попробуй переиспользовать функцию `showNotification`

2021-02-18 10:04 UTC, merged