feat: Add crop image
woohoo1607/manager pull request #24
Opened 2021-02-18 14:53 UTC by woohoo1607

2021-02-19 07:45 UTC, oleksandrbazil requested changes

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/FileInput/index.js
> +    setSrc(URL.createObjectURL(file));
```suggestion
    setFileName(file.name);
    setFieldValue(name, file);
    setSrc(URL.createObjectURL(file));
```
у тебя будет 1(модальное) + 3 рендера, это вызовет дополнительную нагрузку на компонент, просядет performance

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/FileInput/index.js
> +    const file = event.currentTarget.files[0];
где проверка что файл присутствует?
приложение упадет если пользователь не выберет файл в диалоговом окне

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/FileInput/index.js
> +      const croppedImage = await getCroppedImg(imageRef, crop);
те же проблемы:
1) нет проверки что кропнутое изображение пришло  -> упадет приложение
2) многочисленное обновление стейта -> проядет перфоманс

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/FileInput/index.js
> +    const scaleX = image.naturalWidth / image.width;
где деструктуризация?
где гарантия что изображение в функцию пришло?

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/FileInput/index.js
> +    return new Promise((resolve, reject) => {
где обработка ошибок?

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/UI/Modal/styles.css
> +.modal__button:hover {
почему только hover? как насчет focus состояния?

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/UI/Modal/index.js
> +    document.body.classList.add("no-scroll");
а какую проблему должен решить этот useEffect?

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/UI/Modal/ModalHeader.js
> +      <div></div>
зачем пустой div?

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/UI/Modal/ModalHeader.js
> +    <header className="modal__header">
1. Забавно, а почему решил использовать header для модального окна? На всякий случай ссылка [про семантику в HTML](https://msiter.ru/tutorials/html5/semantic_elements) 
- в [bootstrap](https://getbootstrap.com/docs/4.0/components/modal/) не используют
-  в [bulma](https://bulma.io/documentation/components/modal/) используют
2. если у тебя компонент ModalHeader как отдельный компонент - то и стили у него должны лежать рядом
и БЭМ классы по другому написаны

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/UI/Modal/ModalFooter.js
> +      <Button
а мы можем переиспользовать UI/Button?

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/UI/Modal/ModalBody.js
> +const ModalBody = ({ children }) => {
почему вынес в отдельный компонент?

2021-02-19 07:45 UTC, oleksandrbazil commented on src/components/FileInput/index.js
> +      crop.x * scaleX,
🙈

2021-02-19 10:13 UTC, woohoo1607 commented on src/components/UI/Modal/styles.css
> +.modal__button:hover {
добавил

2021-02-19 10:13 UTC, woohoo1607 commented on src/components/UI/Modal/index.js
> +    document.body.classList.add("no-scroll");
блокировать scroll когда открыта модалка

2021-02-19 10:13 UTC, woohoo1607 commented on src/components/UI/Modal/ModalHeader.js
> +      <div></div>
что бы все красиво подравнять с мопощью флекса=)

2021-02-19 10:14 UTC, woohoo1607 commented on src/components/UI/Modal/ModalHeader.js
> +    <header className="modal__header">
сделал одним файлом модалку, теги header и footer поменял на div

2021-02-19 10:15 UTC, woohoo1607 commented on src/components/UI/Modal/ModalBody.js
> +const ModalBody = ({ children }) => {
обьеденил

2021-02-19 12:16 UTC, woohoo1607 commented on src/components/UI/Modal/ModalFooter.js
> +      <Button
есть

2021-02-19 12:22 UTC, woohoo1607 commented on src/components/FileInput/index.js
> +    return new Promise((resolve, reject) => {
та я пример из либы взял=))

2021-02-19 12:25 UTC, woohoo1607 commented on src/components/FileInput/index.js
> +    const scaleX = image.naturalWidth / image.width;
в функции которая вызывает эту функицию есть проверка на изображение

2021-02-19 12:29 UTC, woohoo1607 commented on src/components/FileInput/index.js
> +    const file = event.currentTarget.files[0];
добавил проверку на наличие блоб файла

2021-02-19 12:30 UTC, woohoo1607 commented on src/components/FileInput/index.js
> +    setSrc(URL.createObjectURL(file));
убрал отсюда setFieldValue

2021-02-19 12:30 UTC, woohoo1607 commented on src/components/FileInput/index.js
> +      const croppedImage = await getCroppedImg(imageRef, crop);
добавил проверку на наличие блоб файла

2021-02-19 12:31 UTC, woohoo1607 commented on src/components/FileInput/index.js
> +      crop.x * scaleX,
это с доки=)

2021-02-22 06:56 UTC, oleksandrbazil commented on src/components/FileInput/index.js
> +    return new Promise((resolve, reject) => {
🙉

2021-02-22 06:58 UTC, oleksandrbazil commented on src/components/UI/Modal/ModalHeader.js
> +      <div></div>
делай через классы, я как сторонний кодер просто удалю этот див и не замечу некрасивый дизайн

2021-02-22 06:59 UTC, oleksandrbazil commented on src/components/UI/Modal/index.js
> +    document.body.classList.add("no-scroll");
а почему появляется скрол на документе?

2021-02-22 07:18 UTC, woohoo1607 commented on src/components/UI/Modal/index.js
> +    document.body.classList.add("no-scroll");
он может быть только на мобилках, когда контетнт по высоте больше чем высота экрана, а так вообще всегда ж модалки вроде скролл блокируют=)

2021-02-22 07:50 UTC, oleksandrbazil approved these changes

2021-02-22 08:25 UTC, merged