Feat/network status
woohoo1607/manager pull request #27
Opened 2021-02-26 12:40 UTC by woohoo1607

2021-03-02 12:07 UTC, oleksandrbazil commented on src/components/Header/index.js
> +                <NavLink to={{ pathname: "/logger" }} className={`menu-link`}>
className="menu-link"

2021-03-02 12:07 UTC, oleksandrbazil commented on src/components/LoggerTable/RowItem.js
> +    <span style={{ fontWeight: "bold" }}>{title}:</span> {JSON.stringify(value)}
fontWeight: "bold" как правило лучше реализовать через общий класс, потому что таких мест в проекте может быть сотни

2021-03-02 12:07 UTC, oleksandrbazil commented on src/components/UI/NetworkStatusesList/index.js
> +    <Item status="online" description="the application is online" />
почему не переиспользуешь `const statuses = ["online", "offline", "synchronization", "not-synchronized"];` ?

2021-03-02 12:07 UTC, oleksandrbazil commented on src/components/UI/NetworkStatusesList/styles.css
> +    content: '- ';
почему сделал список через `-` ?

2021-03-02 12:07 UTC, oleksandrbazil commented on src/components/UI/TableHead/styles.css
> +@media screen and (max-width: 479px) {
а можно написать так что бы `table-head` класс был написан только 1 раз?

2021-03-02 12:07 UTC, oleksandrbazil commented on src/pages/HomePage/UserGenerator.js
> +      disabled={disabled}
сделай так что бы компонент мог принимать еще и тип кнопки

2021-03-02 12:07 UTC, oleksandrbazil commented on src/sagas/loggerSaga.js
> +      try {
а почему тут нужен второй try?
что делает yield all() метод в сагах?

2021-03-02 12:07 UTC, oleksandrbazil commented on src/sagas/loggerSaga.js
> +          lastTry: new Date(),
действительно ли важно каждый раз передавать lastTry?

2021-03-02 12:07 UTC, oleksandrbazil commented on src/sagas/usersSagas.js
> +    const isOfflineError = message === FETCH_ERROR;
тебя не смущает повторное использование паттерна?:
```js
const isOfflineError = message === FETCH_ERROR;
    if (isOfflineError) {
      ...
    } else {
      ...
    }
    ```

2021-03-02 12:07 UTC, oleksandrbazil commented on src/services/offlineDb/OfflineUsersService.js
> +          if (foundEmail === email) {
можно как-то избавиться от второй вложенности?

2021-03-02 12:07 UTC, oleksandrbazil commented on src/sagas/loggerSaga.js
> +    watchSynchronizeEventSaga(),
а в чем разница между watchSynchronizeEventsSaga и watchSynchronizeEventSaga?

2021-03-03 07:20 UTC, woohoo1607 commented on src/components/Header/index.js
> +                <NavLink to={{ pathname: "/logger" }} className={`menu-link`}>
исправил

2021-03-03 07:26 UTC, woohoo1607 commented on src/components/LoggerTable/RowItem.js
> +    <span style={{ fontWeight: "bold" }}>{title}:</span> {JSON.stringify(value)}
ок

2021-03-03 07:41 UTC, woohoo1607 commented on src/components/UI/NetworkStatusesList/index.js
> +    <Item status="online" description="the application is online" />
переписал

2021-03-03 07:42 UTC, woohoo1607 commented on src/components/UI/NetworkStatusesList/styles.css
> +    content: '- ';
тире вставляется между названием статуса и его описанием

2021-03-03 07:52 UTC, woohoo1607 commented on src/components/UI/TableHead/styles.css
> +@media screen and (max-width: 479px) {
на чистом css нет

2021-03-03 07:52 UTC, woohoo1607 commented on src/pages/HomePage/UserGenerator.js
> +      disabled={disabled}
компонент Button у меня принимает тип, просто не передал я=)

2021-03-03 07:55 UTC, woohoo1607 commented on src/sagas/loggerSaga.js
> +      try {
второй try нуже для того что бы если какое-то из синхронизируемых событий выполнилось с ошибкой, то другие все равно пытались синхронизироваться. В противном случае если у нас на синхронизацию 10 событий, и первое из них по какой-то причине не может быть синхронизировано, то будет ошибка и другие даже не пошлются

2021-03-03 07:58 UTC, woohoo1607 commented on src/sagas/loggerSaga.js
> +      try {
yield all() - это аналог Promise all. Этот метод ждет завершения всех асинхронных действий которые мы ему передали

2021-03-03 08:00 UTC, woohoo1607 commented on src/sagas/usersSagas.js
> +    const isOfflineError = message === FETCH_ERROR;
частично есть, я думал над этим, но там разная логика немного

2021-03-03 08:00 UTC, woohoo1607 commented on src/sagas/loggerSaga.js
> +          lastTry: new Date(),
ну я его не передаю при создании пользователя, а в других случаях передаю

2021-03-03 08:02 UTC, woohoo1607 commented on src/services/offlineDb/OfflineUsersService.js
> +          if (foundEmail === email) {
ну можно условие первого if добавить через && к другим if, но я решил что так будет более наглядно. Ну и сразу отсеиваем случай если найденый id равняется текущему id.

2021-03-03 08:02 UTC, woohoo1607 commented on src/sagas/loggerSaga.js
> +    watchSynchronizeEventSaga(),
первый для синхронизации всех событий, а второй для синхронизации только одного события

2021-03-03 10:35 UTC, oleksandrbazil commented on src/components/UI/NetworkStatusesList/styles.css
> +    content: '- ';
нет смысла добавлять стили и классы, если можно вставить строку в цикле

2021-03-03 10:41 UTC, oleksandrbazil commented on src/pages/HomePage/UserGenerator.js
> +      disabled={disabled}
я имел ввиду передать тип кнопке через компонент UserGenerator
<UserGenerator type="submit" /> и пробросить его в Button

2021-03-03 10:42 UTC, oleksandrbazil commented on src/components/UI/TableHead/styles.css
> +@media screen and (max-width: 479px) {
было бы здорово что-то сделать что бы не писать класс второй раз. как насчет scss?

2021-03-03 10:45 UTC, oleksandrbazil commented on src/sagas/loggerSaga.js
> +      try {
а какие методы есть в Redux Saga? посмотри что может тебе подойти для этой задачи
потому что использовать try catch в цикле - плохая идея

2021-03-03 10:45 UTC, oleksandrbazil commented on src/sagas/loggerSaga.js
> +          lastTry: new Date(),
я бы писал так что бы не передавать одни и те же параметры

2021-03-03 10:48 UTC, oleksandrbazil commented on src/sagas/usersSagas.js
> +    const isOfflineError = message === FETCH_ERROR;
попробуй придумать как можно сделать эту обработку :)

2021-03-03 10:52 UTC, oleksandrbazil commented on src/services/offlineDb/OfflineUsersService.js
> +          if (foundEmail === email) {
то есть валидация для текущего пользователя никогда не сработает?

2021-03-03 10:56 UTC, oleksandrbazil commented on src/sagas/loggerSaga.js
> +    watchSynchronizeEventSaga(),
думаю что нужно использовать одиночные watcher-ы , а синхронизацию множества записей сделать так что бы периспользовать одиночный watcher? 
что думаешь по этому поводу?

2021-03-03 10:57 UTC, oleksandrbazil requested changes
...

2021-03-03 11:00 UTC, woohoo1607 commented on src/services/offlineDb/OfflineUsersService.js
> +          if (foundEmail === email) {
валидация работает, просто если при валидации был найден уже такой емейл в БД, и при этом это емейл данного пользователя, то это ж не проблема=)

2021-03-03 12:08 UTC, woohoo1607 commented on src/components/UI/NetworkStatusesList/styles.css
> +    content: '- ';
переписал

2021-03-03 15:34 UTC, woohoo1607 commented on src/sagas/loggerSaga.js
> +      try {
эту сагу вообще удалил

2021-03-03 15:34 UTC, woohoo1607 commented on src/sagas/loggerSaga.js
> +    watchSynchronizeEventSaga(),
сделал именно так

2021-03-03 15:57 UTC, oleksandrbazil approved these changes
мердж

2021-03-03 21:30 UTC, merged