Feat/step wizard step2
woohoo1607/manager pull request #3
Opened 2021-01-25 11:52 UTC by woohoo1607

2021-01-25 12:31 UTC, oleksandrbazil requested changes

2021-01-25 12:31 UTC, oleksandrbazil commented on package.json
> +    "react-datepicker": "^3.4.1",
а почему поменял библиотеку?

2021-01-25 12:31 UTC, oleksandrbazil commented on package.json
> +    "web-vitals": "^1.1.0",
зачем этот пакет в зависимости?

2021-01-25 12:31 UTC, oleksandrbazil commented on src/components/Button/index.js
> +  gray: {
у тебя по идее не должно быть gray button. Где ее используют?

2021-01-25 12:31 UTC, oleksandrbazil commented on src/components/Button/index.js
> +        ...btnColors[color],
перепиши, пожалуйста, на классы согласно БЭМ

2021-01-25 12:31 UTC, oleksandrbazil commented on src/components/Button/index.js
> +      {children}
👍

2021-01-25 12:31 UTC, oleksandrbazil commented on src/components/Input/DateInput.js
> +        selected={(value && new Date(value)) || null}
выглядит опасно, что у тебя лежит в value? какой тип данных?

2021-01-25 12:31 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +  { title: "Capabilities", type: "disabled" },
как думаешь это правильный подход?

2021-01-25 12:31 UTC, oleksandrbazil commented on src/containers/StepWizardContainer/reducer.js
> +  gender: "Male",
почему по умолчанию Male?
давай не будем выбирать гендер по умолчанию

2021-01-25 12:31 UTC, oleksandrbazil commented on src/containers/StepWizardContainer/index.js
> +    },
как думаешь что можно здесь написать лучше?

2021-01-25 12:31 UTC, oleksandrbazil commented on src/containers/StepWizardContainer/index.js
> +  const user = useSelector((state) => state.user);
так не пойдет, StepWizard не должен быть привязанным к user
Мы планируем переиспользовать этот компонент для создания Профессии

2021-01-25 12:31 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +const StepWizard = ({ nextStep, user, steps, activeStep, previousStep }) => {
StepWizard это название для компонента который можно переиспользовать, в этом случае тут название должно быть частным, как думаешь каким?

2021-01-25 12:31 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardHeader.js
> +                <Button type={item.type} style={btnStyles}>
а как правильно блокировать кнопку через HTML?

2021-01-25 12:31 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardBody.js
> +            <div className="step-wizard-left">
представь что есть Step # 3 у которого нет разделения на 2 коллонки, это одна форма с полями на всю ширину
**Вопрос:** как отобразить эту форму в такой структуре?

2021-01-25 12:31 UTC, oleksandrbazil commented on src/components/Input/index.js
> +      {inputType === "date" && (
как тебе этот компонент в целом? как его можно улучшить что бы читалось легче и суть передавалась?

2021-01-25 12:31 UTC, oleksandrbazil commented on src/components/Input/styles.css
> +.react-datepicker__header {
смотри: компонент Input а стили не для всех инпутов а только для Datetime
Хороший ли это подход?

2021-01-25 12:31 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +      {activeStep === 1 && (
так надо будет писать каждый раз?

2021-01-25 12:33 UTC, woohoo1607 commented on package.json
> +    "react-datepicker": "^3.4.1",
поставил либу на которую была ссылка в ТЗ

2021-01-25 12:36 UTC, woohoo1607 commented on package.json
> +    "web-vitals": "^1.1.0",
Реакт начал ругаться, этот пакет из коробки идет, поэтому решил вернуть, а не удалять файл связаный с этой либой

2021-01-25 12:38 UTC, woohoo1607 commented on src/components/Button/index.js
> +  gray: {
эти переменные задавали цвет, поэтому я их переименовал. Кнопка "Back" в форме серого цвета.

2021-01-25 12:43 UTC, woohoo1607 commented on src/components/Input/DateInput.js
> +        selected={(value && new Date(value)) || null}
или дата или пустая строка, если дата не выбрана

2021-01-25 12:44 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +  { title: "Capabilities", type: "disabled" },
думаю нет=) П.С. я поле type уже не использую, сейчас удалю его=)

2021-01-25 12:46 UTC, woohoo1607 commented on src/containers/StepWizardContainer/reducer.js
> +  gender: "Male",
ок, просто в макете там стояло активное, поэтому и поставил=)

2021-01-25 12:48 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardHeader.js
> +                <Button type={item.type} style={btnStyles}>
через тег disabled. Там не то подразумевалось изначально=) удалил это вообще

2021-01-25 12:53 UTC, woohoo1607 commented on src/containers/StepWizardContainer/index.js
> +  const user = useSelector((state) => state.user);
тогда нужно reducer, actions и получение данных вынести в NewUserPage?

2021-01-25 12:54 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +const StepWizard = ({ nextStep, user, steps, activeStep, previousStep }) => {
если имеется ввиду название переменной user, то тогда можно ее переименовать на data

2021-01-25 12:55 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardBody.js
> +            <div className="step-wizard-left">
наверное никак, просто в макете везде разделено на 2 части, вот так и запилил

2021-01-25 13:00 UTC, woohoo1607 commented on src/components/Input/styles.css
> +.react-datepicker__header {
вынес в отдельный файл

2021-01-25 13:06 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +      {activeStep === 1 && (
Я исправил, но теперь есть вопрос=)

2021-01-25 13:09 UTC, woohoo1607 commented on src/components/Input/index.js
> +      {inputType === "date" && (
переписал через тернарный оператор проверку на тип дата

2021-01-25 13:11 UTC, woohoo1607 commented on src/containers/StepWizardContainer/index.js
> +    },
`const addData = useCallback((data) => dispatch(addAccountData({ ...data })), [
    dispatch,
  ]);`
переписал так

2021-01-25 17:39 UTC, oleksandrbazil commented on src/components/Input/index.js
> +      {inputType === "date" && (
нет, проблема немного глубже:
в этом компоненте идет отображение согласно inputType
Вопрос: может ли inputType изменяться динамически на другой или он всегда будет таким как описано в компоненте?

2021-01-25 17:41 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +      {activeStep === 1 && (
какой вопрос? актуально?

2021-01-25 21:03 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +      {activeStep === 1 && (
Уже нет:)

2021-01-25 21:04 UTC, woohoo1607 commented on src/components/Input/index.js
> +      {inputType === "date" && (
Динамически не меняется

2021-01-26 08:30 UTC, oleksandrbazil commented on src/components/Input/index.js
> +      {inputType === "date" && (
в таком случае нужно разделить логику
- базовое отображение Input в одном компоненте (с возможностью добавить классы и стили)
- логика работы password с возможностью подсмотреть пароль в другом (на основе базового отображения)
- логика датапикера и собственно новых стилей в третем (на основе базового отображения)

make sense?

2021-01-26 08:32 UTC, oleksandrbazil commented on src/components/UserForms/InputItem.js
> +const InputItem = ({ name, title, type, className }) => {
название не очень отображает суть, какие есть еще варианты?

2021-01-26 08:38 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +      <StepWizard steps={steps} data={user} saveStep={saveStep} />
что такое saveStep?
кто должен отвечать за сохранение?

2021-01-26 08:41 UTC, woohoo1607 commented on src/pages/NewUserPage/index.js
> +      <StepWizard steps={steps} data={user} saveStep={saveStep} />
saveStep - сохраняет данные введенные в форме и переходит на следующую форму.
Если назвать nextStep, а для сохранения потом сделать функцию save?

2021-01-26 08:51 UTC, oleksandrbazil commented on src/pages/NewUserPage/index.js
> +      <StepWizard steps={steps} data={user} saveStep={saveStep} />
StepWizard отвечает за сохранение данных или AccountForm/ProfileForm?

2021-01-26 12:19 UTC, oleksandrbazil approved these changes
есть моменты которые надо поправить, но лучше позже, мердж в main

2021-01-26 12:21 UTC, merged