refactor: Refactor user forms
woohoo1607/manager pull request #5
Opened 2021-01-26 13:52 UTC by woohoo1607

2021-01-26 13:58 UTC, oleksandrbazil commented on src/components/UserForms/AccountForm.js
> +    className: "account-form__input",
приставки account не должно быть :)

2021-01-26 15:15 UTC, oleksandrbazil requested changes

2021-01-26 15:15 UTC, oleksandrbazil commented on src/components/UserForms/AccountForm.js
> +import PasswordInput from "../PasswordInput/PasswordInput";
переделай на index.js

2021-01-26 15:15 UTC, oleksandrbazil commented on src/components/UserForms/ProfileForm.js
> +import Input from "../Input";
перемести Input в папку ui
`import Input from "../UI/Input";`

2021-01-26 15:15 UTC, oleksandrbazil commented on src/components/UserForms/ProfileForm.js
> +          isRequired={true}
как можно передать этот параметр проще?

2021-01-26 15:15 UTC, oleksandrbazil commented on src/components/UserForms/ProfileForm.js
> +          style={inputStyle}
почему мы постоянно прокидываем style? 
почему эти стили нельзя определить в `ui/Input`?

2021-01-26 15:15 UTC, oleksandrbazil commented on src/components/UserForms/ProfileForm.js
> +          {...props}
какие параметры прокидываешь?

2021-01-26 15:15 UTC, oleksandrbazil commented on src/components/UserForms/ProfileForm.js
> +        <div className="profile-form__button-container">
чем profile-form отличается от account-form?

2021-01-26 15:15 UTC, oleksandrbazil commented on src/components/UserForms/LayoutForm.js
> +            style={showInRow ? { ...inRowStyles, styles } : styles}
что это за  showInRow?

2021-01-26 15:15 UTC, oleksandrbazil commented on src/components/UserForms/AccountForm.js
> +        <PasswordInput
зачем нам передавать `type=password` в `PasswordInput`?

2021-01-26 15:15 UTC, oleksandrbazil commented on src/components/DateInput/index.js
> +const DateInput = ({ title, name, type, isRequired, style }) => {
все параметры обязательные? почему не определяешь значения по умолчанию?

2021-01-26 15:32 UTC, woohoo1607 commented on src/components/UserForms/AccountForm.js
> +import PasswordInput from "../PasswordInput/PasswordInput";
переделал

2021-01-26 15:34 UTC, woohoo1607 commented on src/components/UserForms/ProfileForm.js
> +import Input from "../Input";
сделал

2021-01-26 15:36 UTC, woohoo1607 commented on src/components/UserForms/ProfileForm.js
> +          isRequired={true}
просто передавать в компонент isRequired

2021-01-26 15:37 UTC, woohoo1607 commented on src/components/UserForms/ProfileForm.js
> +          style={inputStyle}
я там ширину контейнера для input передаю, в разных местах она разная

2021-01-26 15:40 UTC, oleksandrbazil commented on src/components/UserForms/ProfileForm.js
> +import Input from "../Input";
пуш

2021-01-26 15:40 UTC, oleksandrbazil commented on src/components/UserForms/ProfileForm.js
> +          isRequired={true}
пуш

2021-01-26 15:45 UTC, woohoo1607 commented on src/components/UserForms/ProfileForm.js
> +          {...props}
деструктуризировал что бы понятно было

2021-01-26 15:49 UTC, woohoo1607 commented on src/components/UserForms/ProfileForm.js
> +        <div className="profile-form__button-container">
контейнер для кнопок разные стили имеет, margin, display

2021-01-26 15:50 UTC, woohoo1607 commented on src/components/UserForms/LayoutForm.js
> +            style={showInRow ? { ...inRowStyles, styles } : styles}
если true, то все что в форме позиционируется в ряд через display: flex

2021-01-26 15:50 UTC, woohoo1607 commented on src/components/UserForms/AccountForm.js
> +        <PasswordInput
забыл убрать=)

2021-01-26 15:54 UTC, woohoo1607 commented on src/components/DateInput/index.js
> +const DateInput = ({ title, name, type, isRequired, style }) => {
убрал type, потому что всегда будет "date"
style, isRequired - не обязательный
title - если не будет то тоже ничего страшного не случится

2021-01-27 08:12 UTC, oleksandrbazil requested changes

2021-01-27 08:12 UTC, oleksandrbazil commented on src/components/DateInput/index.js
> +import InputLayout from "../UI/Input2/InputLayout";
не должно быть названий по типу SomeName2

2021-01-27 08:12 UTC, oleksandrbazil commented on src/components/InputField/index.js
> +          <InputLayout>
что такое InputLayout?

2021-01-27 08:12 UTC, oleksandrbazil commented on src/components/UI/Input2/index.js
> +const Input = ({ title, type, name, isRequired, children, style }) => {
не понимаю зачем тут 2 компонента?

2021-01-27 08:12 UTC, oleksandrbazil commented on src/components/UI/InputTitle/index.js
> +      <p className="input-title">{title}</p>
почитай про свойства тегов `p` и `span`
как по мне тут можно обойтись одним div/p + span

2021-01-27 08:12 UTC, oleksandrbazil commented on src/components/UserForms/AccountForm.js
> +        <InputField
почему нужно дергать InputField? почему нельзя сразу использовать PasswordInput?

2021-01-27 08:13 UTC, woohoo1607 commented on src/components/DateInput/index.js
> +import InputLayout from "../UI/Input2/InputLayout";
это что бы приложение не крашнулось, оставил пока старый инпут

2021-01-27 08:13 UTC, woohoo1607 commented on src/components/UI/Input2/index.js
> +const Input = ({ title, type, name, isRequired, children, style }) => {
еще не удалил старое

2021-01-27 08:15 UTC, woohoo1607 commented on src/components/InputField/index.js
> +          <InputLayout>
просто контейнер для инпута (div с классом 'input-container')

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/Button/styles.css
> +.input-img {
что делают стили инпута в стиях кнопки?

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/DateInput/index.js
> +        useWeekdaysShort={true}
... ?)

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/FormikField/index.js
> +            {React.cloneElement(children, {
зачем react.cloneElement?

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/RadioGroup/index.js
> +  const currentValue = currentValues ? currentValues[name] : "";
что за тип данных в currentValues?

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +            : "step-wizard__button"
замечаю уже не первый раз с тернарным оператором когда основной класс пишется дважды (тут это `step-wizard__button`). Зачем?

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardHeader.js
> +  };
привет 👋 а почему ты не пишешь сокращенно где это возможно?

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +          className="step-wizard__button step-wizard__button-back"
что делает класс `step-wizard__button-back` ?

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const stepsCnt = steps.length;
Пожалуйста, не сокращай название - лучше пиши полностью. Если видишь что длинное слово, постарайся найти применимый аналог покороче

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +  const stepsCnt = steps.length;
а зачем вообще выносить это в переменную?

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/StepWizard/index.js
> +        <CurrentFrom {...data} nextStep={nextStep}>
может есть смысл передать сразу компонент? :)

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/StepWizard/styles.css
> +.step-wizard__button {
пустой класс

2021-01-27 11:47 UTC, oleksandrbazil commented on src/components/UI/InputTitle/index.js
> +    <div className="input-title-container">
а контейнер реально нужен для title?

2021-01-27 12:49 UTC, woohoo1607 commented on src/components/Button/styles.css
> +.input-img {
это стиль позиционирования кнопки для инпута=)

2021-01-27 12:49 UTC, woohoo1607 commented on src/components/DateInput/index.js
> +        useWeekdaysShort={true}
укоротил

2021-01-27 12:50 UTC, woohoo1607 commented on src/components/FormikField/index.js
> +            {React.cloneElement(children, {
а как я передам пропсы children`у?=)

2021-01-27 12:50 UTC, woohoo1607 commented on src/components/RadioGroup/index.js
> +  const currentValue = currentValues ? currentValues[name] : "";
строка

2021-01-27 12:54 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardControls.js
> +            : "step-wizard__button"
а цвет кнопки прям тут через style поменять?

2021-01-27 12:54 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardHeader.js
> +  };
укоротил

2021-01-27 12:55 UTC, woohoo1607 commented on src/components/StepWizard/StepWizardControls.js
> +          className="step-wizard__button step-wizard__button-back"
цвет меняет

2021-01-27 12:56 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +  const stepsCnt = steps.length;
поправил

2021-01-27 12:59 UTC, woohoo1607 commented on src/components/StepWizard/index.js
> +        <CurrentFrom {...data} nextStep={nextStep}>
а как это правильно сделать? CurrentForm это ж и есть наш текущий компонент

2021-01-27 13:00 UTC, woohoo1607 commented on src/components/StepWizard/styles.css
> +.step-wizard__button {
удалил

2021-01-27 13:01 UTC, woohoo1607 commented on src/components/UI/InputTitle/index.js
> +    <div className="input-title-container">
я потом на его основе позиционирывал кнопку для инпута

2021-01-27 13:56 UTC, oleksandrbazil commented on src/components/StepWizard/StepWizardControls.js
> +          className="step-wizard__button step-wizard__button-back"
а параметр color тогда зачем?

2021-01-27 14:39 UTC, oleksandrbazil approved these changes

2021-01-27 15:59 UTC, merged